# topic_model_pretrainer_cloud/config_pretrainer.py
import os
# health_topics_data.py should be in the same directory or your PYTHONPATH
# It contains your master HEALTH_TOPICS_KEYWORDS dictionary (with English keyword strings)
# For this config, we'll use the master list directly for seeding BERTopic,
# and the manually/semi-automatically generated keyword lists below for filtering Wikipedia.
from health_topics_data import HEALTH_TOPICS_KEYWORDS as MASTER_HEALTH_TOPIC_DESCRIPTIONS_FOR_SEEDING

# --- General Paths ---
BASE_PROJECT_DIR = os.path.abspath(os.path.dirname(__file__)) # Root of this pretrainer project
WORKING_DIR = os.path.join(BASE_PROJECT_DIR, "pretrainer_workspace")

# --- Wikipedia Data Paths ---
WIKIPEDIA_DUMP_DIR = os.path.join(WORKING_DIR, "wikipedia_dumps")
WIKIPEDIA_GENSIM_EXTRACTED_TEXT_DIR = os.path.join(WORKING_DIR, "wikipedia_gensim_extracted")
FILTERED_WIKIPEDIA_TEXT_DIR = os.path.join(WORKING_DIR, "wikipedia_filtered_texts_gensim")

LANGUAGES_TO_PROCESS = ["en", "fr", "ar"] # Processing all three languages

# --- SBERT Model ---
SBERT_MODEL_NAME = "paraphrase-multilingual-mpnet-base-v2"
SBERT_MODEL_SAVE_PATH = os.path.join(WORKING_DIR, "sbert_model")

# --- BERTopic Model Output ---
FINAL_BERTOPIC_OUTPUT_DIR = os.path.join(WORKING_DIR, "bertopic_model_final_output_multilang_gensim")
FINAL_BERTOPIC_MODEL_FILENAME = "bertopic_model_final_guided_multilang_gensim.joblib"
FINAL_BERTOPIC_FULL_PATH = os.path.join(FINAL_BERTOPIC_OUTPUT_DIR, FINAL_BERTOPIC_MODEL_FILENAME)

# BERTopic training parameters
WIKIPEDIA_ARTICLES_PER_LANGUAGE_LIMIT: dict[str, int] = {
    "en": 50000,
    "fr": 30000,
    "ar": 20000
}
BERTOPIC_MIN_TOPIC_SIZE = 20
BERTOPIC_NR_TOPICS = None

SEED_KEYWORD_MIN_LEN = 3
SEED_MAX_KEYWORDS_PER_TOPIC = 7

# --- Filtering settings for Wikipedia articles (using gensim output) ---
# These dictionaries map keys from your MASTER_HEALTH_TOPIC_DESCRIPTIONS_FOR_SEEDING
# to lists of keywords for filtering Wikipedia articles in each language.

HEALTH_CATEGORIES_KEYWORDS_EN: dict[str, list[str]] = {
    "symptoms_general": ["general symptoms", "systemic symptoms", "fatigue", "malaise", "weakness", "weight changes", "appetite changes", "night sweats", "asthenia"],
    "symptoms_fever_temperature": ["fever", "high temperature", "hypothermia", "chills", "shivering", "pyrexia", "febrile"],
    "symptoms_respiratory_upper": ["upper respiratory", "runny nose", "rhinorrhea", "nasal congestion", "sneezing", "sore throat", "pharyngitis", "loss of voice", "hoarseness", "laryngitis"],
    "symptoms_respiratory_lower": ["lower respiratory", "cough", "dry cough", "productive cough", "sputum", "shortness of breath", "dyspnea", "wheezing", "chest tightness", "breathing pain", "hemoptysis"],
    "symptoms_cardiovascular": ["cardiovascular", "chest pain", "angina", "palpitations", "irregular heartbeat", "arrhythmia", "edema", "swelling legs", "swelling ankles", "fainting", "syncope", "high blood pressure", "low blood pressure", "hypertension", "hypotension"],
    "symptoms_gastrointestinal_upper": ["upper gi", "nausea", "vomiting", "emesis", "heartburn", "acid reflux", "gerd", "indigestion", "dyspepsia", "difficulty swallowing", "dysphagia"],
    "symptoms_gastrointestinal_lower": ["lower gi", "diarrhea", "constipation", "abdominal pain", "abdominal cramps", "bloating", "flatulence", "gas", "blood in stool", "melena", "rectal bleeding", "jaundice", "icterus"],
    "symptoms_neurological": ["neurological", "headache", "migraine", "dizziness", "vertigo", "confusion", "disorientation", "memory loss", "amnesia", "loss of consciousness", "seizures", "convulsions", "tremors", "numbness", "tingling", "paresthesia", "weakness", "paralysis", "balance problems", "ataxia", "loss of smell", "anosmia", "loss of taste", "ageusia"],
    "symptoms_musculoskeletal": ["musculoskeletal", "muscle aches", "myalgia", "joint pain", "arthralgia", "back pain", "neck pain", "stiffness", "joint swelling", "muscle cramps", "bone pain"],
    "symptoms_skin_integumentary": ["skin symptoms", "rash", "hives", "urticaria", "itching", "pruritus", "lesions", "skin sores", "skin ulcers", "blisters", "dry skin", "scaling skin", "sweating changes", "skin discoloration", "hair loss", "alopecia", "nail changes"],
    "symptoms_eyes_vision": ["eye symptoms", "vision symptoms", "red eyes", "conjunctivitis", "eye pain", "blurred vision", "double vision", "diplopia", "light sensitivity", "photophobia", "eye discharge", "vision loss", "blindness"],
    "symptoms_ears_hearing": ["ear symptoms", "hearing symptoms", "ear pain", "otalgia", "hearing loss", "deafness", "tinnitus", "ringing in ears", "ear discharge", "otorrhea", "vertigo ear"],
    "symptoms_urinary_renal": ["urinary symptoms", "kidney symptoms", "painful urination", "dysuria", "frequent urination", "urinary urgency", "blood in urine", "hematuria", "incontinence", "flank pain", "decreased urine output", "oliguria", "anuria"],
    "symptoms_reproductive_public": ["reproductive health", "menstrual irregularities", "pelvic pain", "abnormal bleeding", "fertility issues"],
    "symptoms_lymphatic_hematologic": ["lymphatic symptoms", "blood symptoms", "swollen lymph nodes", "lymphadenopathy", "easy bruising", "unexplained bleeding", "anemia", "petechiae"],
    "disease_covid19": ["covid-19", "covid", "omicron", "delta variant", "long covid", "pasc", "coronavirus", "sars-cov-2", "pandemic", "covid symptoms", "covid infection"],
    "disease_influenza_seasonal": ["seasonal influenza", "flu", "influenza", "h1n1", "h3n2", "influenza b", "grippe", "influenza-like illness", "ili"],
    "disease_influenza_avian_pandemic": ["avian influenza", "bird flu", "h5n1", "h7n9", "pandemic flu", "influenza pandemic"],
    "disease_rsv": ["respiratory syncytial virus", "rsv", "bronchiolitis"],
    "disease_common_cold": ["common cold", "rhinovirus", "adenovirus cold", "nasopharyngitis"],
    "disease_measles": ["measles", "rubeola", "measles virus", "koplik spots", "measles rash"],
    "disease_mumps": ["mumps", "parotitis", "mumps virus", "swollen salivary glands"],
    "disease_rubella": ["rubella", "german measles", "congenital rubella syndrome"],
    "disease_chickenpox_shingles": ["varicella-zoster virus", "vzv", "chickenpox", "varicella", "shingles", "herpes zoster"],
    "disease_tuberculosis": ["tuberculosis", "tb", "mycobacterium tuberculosis", "pulmonary tb", "extrapulmonary tb", "mdr-tb", "xdr-tb", "consumption"],
    "disease_pertussis": ["pertussis", "whooping cough", "bordetella pertussis"],
    "disease_pneumonia_bacterial": ["bacterial pneumonia", "streptococcus pneumoniae", "pneumococcus", "haemophilus influenzae pneumonia", "mycoplasma pneumonia", "legionella pneumonia"],
    "disease_diphtheria": ["diphtheria", "corynebacterium diphtheriae"],
    "disease_legionnaires": ["legionnaires' disease", "legionellosis", "legionella pneumophila"],
    "disease_norovirus": ["norovirus", "acute gastroenteritis", "stomach flu", "winter vomiting bug"],
    "disease_rotavirus": ["rotavirus", "rotavirus vaccine", "infant diarrhea"],
    "disease_salmonellosis": ["salmonella", "salmonellosis", "food poisoning salmonella", "nontyphoidal salmonella"],
    "disease_shigellosis": ["shigella", "shigellosis", "bacillary dysentery"],
    "disease_ecoli_pathogenic": ["pathogenic e. coli", "ehec", "o157:h7", "stec", "e. coli infection"],
    "disease_campylobacteriosis": ["campylobacter", "campylobacteriosis", "food poisoning campylobacter"],
    "disease_cholera": ["cholera", "vibrio cholerae"],
    "disease_typhoid_paratyphoid": ["typhoid fever", "enteric fever", "salmonella typhi", "paratyphoid fever", "salmonella paratyphi"],
    "disease_giardiasis": ["giardia", "giardiasis", "giardia lamblia", "beaver fever"],
    "disease_amebiasis": ["amebiasis", "entamoeba histolytica", "amebic dysentery"],
    "disease_listeriosis": ["listeria", "listeriosis", "listeria monocytogenes", "foodborne listeria"],
    "disease_hepatitis_a_e": ["hepatitis a", "hav", "hepatitis e", "hev", "foodborne hepatitis", "waterborne hepatitis"],
    "disease_west_nile_virus": ["west nile virus", "wnv", "west nile fever", "west nile encephalitis", "mosquito-borne wnv"],
    "disease_dengue": ["dengue fever", "dengue hemorrhagic fever", "dengue shock syndrome", "breakbone fever", "aedes mosquito dengue"],
    "disease_chikungunya": ["chikungunya", "chikungunya virus", "aedes mosquito chikungunya"],
    "disease_leishmaniasis": ["leishmaniasis", "cutaneous leishmaniasis", "visceral leishmaniasis", "kala-azar", "sandfly leishmaniasis"],
    "disease_malaria": ["malaria", "plasmodium falciparum", "plasmodium vivax", "anopheles mosquito", "antimalarial"],
    "disease_rift_valley_fever": ["rift valley fever", "rvf", "zoonotic rvf", "mosquito-borne rvf"],
    "disease_crimean_congo_hemorrhagic": ["crimean-congo hemorrhagic fever", "cchf", "tick-borne cchf", "viral hemorrhagic fever cchf"],
    "disease_tick_borne_encephalitis": ["tick-borne encephalitis", "tbe", "tick-borne fever"],
    "disease_rabies": ["rabies", "hydrophobia", "animal bite rabies", "rabies virus"],
    "disease_brucellosis": ["brucellosis", "malta fever", "undulant fever", "brucella"],
    "disease_anthrax": ["anthrax", "bacillus anthracis", "cutaneous anthrax", "inhalation anthrax", "gastrointestinal anthrax"],
    "disease_leptospirosis": ["leptospirosis", "weil's disease", "leptospira"],
    "disease_q_fever": ["q fever", "coxiella burnetii"],
    "disease_mpox": ["mpox", "monkeypox", "monkeypox virus"],
    "disease_ebola_marburg": ["ebola virus disease", "evd", "marburg virus disease", "mvd", "filovirus", "viral hemorrhagic fever ebola"],
    "disease_scabies_lice": ["scabies", "sarcoptes scabiei", "head lice", "pediculosis", "nits", "lice infestation"],
    "disease_hiv_aids": ["hiv", "human immunodeficiency virus", "aids", "acquired immunodeficiency syndrome", "antiretroviral therapy", "art"],
    "disease_hepatitis_b_c": ["hepatitis b", "hbv", "hepatitis c", "hcv", "chronic hepatitis", "liver cirrhosis hepatitis", "liver cancer hepatitis"],
    "disease_syphilis": ["syphilis", "treponema pallidum", "congenital syphilis", "neurosyphilis"],
    "disease_gonorrhea": ["gonorrhea", "neisseria gonorrhoeae", "the clap"],
    "disease_chlamydia": ["chlamydia", "chlamydia trachomatis"],
    "disease_hpv": ["human papillomavirus", "hpv", "cervical cancer hpv", "genital warts", "hpv vaccine"],
    "disease_meningitis_bacterial": ["bacterial meningitis", "neisseria meningitidis", "meningococcus", "streptococcus pneumoniae meningitis", "haemophilus influenzae type b", "hib meningitis"],
    "disease_meningitis_viral": ["viral meningitis", "aseptic meningitis", "enterovirus meningitis", "hsv meningitis"],
    "disease_tetanus": ["tetanus", "lockjaw", "clostridium tetani", "tetanus toxoid"],
    "disease_poliomyelitis": ["polio", "poliomyelitis", "poliovirus", "infantile paralysis", "post-polio syndrome", "vdpv"],
    "transmission_airborne_droplet": ["airborne transmission", "droplet transmission", "respiratory droplets", "aerosol transmission", "spread through air"],
    "transmission_foodborne": ["foodborne illness", "food poisoning", "contaminated food", "food safety"],
    "transmission_waterborne": ["waterborne illness", "contaminated water", "water safety", "unsafe water"],
    "transmission_vector_mosquito": ["mosquito-borne disease", "mosquito vector", "aedes", "anopheles", "culex"],
    "transmission_vector_tick": ["tick-borne disease", "tick vector", "ixodes", "dermacentor"],
    "transmission_vector_other": ["vector-borne disease", "sandfly", "flea", "fly vector", "tsetse fly"],
    "transmission_zoonotic": ["zoonotic disease", "zoonosis", "animal to human", "animal reservoirs", "spillover"],
    "transmission_direct_contact": ["direct contact transmission", "skin-to-skin contact", "mucous membrane contact"],
    "transmission_fecal_oral": ["fecal-oral route", "fecal contamination", "oral ingestion"],
    "transmission_bloodborne_sexual": ["bloodborne pathogen", "sexually transmitted infection", "sti", "std", "bodily fluids transmission"],
    "transmission_healthcare_associated": ["healthcare-associated infection", "hai", "nosocomial infection", "hospital-acquired infection", "iatrogenic"],
    "transmission_congenital_perinatal": ["congenital transmission", "perinatal transmission", "mother-to-child transmission", "vertical transmission"],
    "disease_type_viral_hemorrhagic": ["viral hemorrhagic fever", "vhf", "ebola", "marburg", "lassa", "cchf"],
    "disease_type_prion": ["prion disease", "creutzfeldt-jakob disease", "cjd", "transmissible spongiform encephalopathy", "tse"],
    "public_health_surveillance_reporting": ["disease surveillance", "case reporting", "epidemiological report", "outbreak investigation", "public health data", "case counts"],
    "public_health_prevention_hygiene": ["prevention", "hygiene practices", "handwashing", "cough etiquette", "sanitation", "disease prevention"],
    "public_health_vaccination_campaigns": ["vaccination campaign", "immunization drive", "vaccine rollout", "vaccine eligibility", "mass vaccination"],
    "public_health_vaccination_hesitancy": ["vaccine hesitancy", "vaccine refusal", "anti-vaccination", "vaccine misinformation", "vaccine safety concerns"],
    "public_health_vaccination_access_supply": ["vaccine access", "vaccine supply", "vaccine shortage", "vaccine distribution", "vaccine appointment"],
    "public_health_vaccination_aefi": ["adverse events following immunization", "aefi", "vaccine side effects reporting"],
    "public_health_npi_distancing_limits": ["social distancing", "physical distancing", "capacity limits", "gathering restrictions", "stay-at-home order"],
    "public_health_npi_closures": ["school closure", "business closure", "lockdown", "curfew", "non-pharmaceutical interventions"],
    "public_health_screening_testing_strategy": ["disease screening", "diagnostic testing", "mass testing", "pcr test", "rapid antigen test", "testing strategy"],
    "public_health_screening_testing_access": ["test availability", "testing access", "test cost", "testing centers", "home testing kit"],
    "public_health_contact_tracing": ["contact tracing", "exposure notification", "case investigation"],
    "public_health_quarantine_isolation": ["quarantine", "isolation", "self-isolation", "quarantine period"],
    "public_health_border_control_travel": ["travel advisory", "border closure", "travel restrictions", "entry requirements", "airport screening", "imported cases"],
    "public_health_communication_alerts": ["public health announcement", "health alert", "risk communication", "health advisory", "emergency communication"],
    "public_health_misinformation_disinformation": ["health misinformation", "health disinformation", "fake news health", "rumors health", "fact checking health"],
    "public_health_policy_legislation": ["public health policy", "health legislation", "government health regulation", "health funding"],
    "public_health_vector_control": ["vector control", "mosquito control", "tick control", "rodent control", "insecticide spraying"],
    "public_health_food_safety_regulation": ["food safety", "food regulation", "food inspection", "restaurant hygiene"],
    "public_health_research_studies": ["public health research", "clinical trial", "epidemiological study", "health study"],
    "health_system_capacity_hospitals": ["hospital capacity", "bed availability", "icu beds", "emergency room capacity", "hospital overcrowding", "patient wait times"],
    "health_system_capacity_staffing": ["healthcare staffing", "doctor shortage", "nurse shortage", "healthcare worker burnout", "medical staff strike"],
    "health_system_capacity_equipment": ["medical equipment shortage", "ventilator availability", "oxygen supply", "ppe shortage", "personal protective equipment"],
    "health_system_access_primary_care": ["primary care access", "gp access", "family doctor access", "preventive care", "health checkup access"],
    "health_system_access_specialist_care": ["specialist access", "specialist consultation", "wait list specialist", "referral specialist"],
    "health_system_access_geographic_rural": ["rural healthcare", "underserved area healthcare", "geographic access barriers", "mobile clinics"],
    "health_system_access_cost_affordability": ["healthcare cost", "medical bill", "out-of-pocket health expense", "affordable healthcare", "health affordability"],
    "health_system_access_insurance": ["health insurance", "cnam", "private health insurance", "uninsured", "underinsured", "insurance coverage"],
    "health_system_pharmaceuticals_supply": ["medication supply", "drug shortage", "pharmacy stock", "vaccine supply chain"],
    "health_system_pharmaceuticals_cost": ["medication cost", "drug price", "prescription cost", "affordable medicine"],
    "health_system_pharmaceuticals_safety": ["drug safety", "medication error", "counterfeit drug", "adverse drug reaction"],
    "health_system_diagnostics_labs": ["diagnostic lab access", "lab test availability", "imaging service access", "x-ray mri delay"],
    "health_system_emergency_services": ["emergency medical service", "ems", "ambulance service", "ambulance response time", "emergency care"],
    "health_system_telehealth": ["telehealth", "telemedicine", "remote consultation", "virtual doctor visit"],
    "health_system_quality_of_care": ["quality of care", "patient safety", "medical error", "patient satisfaction", "healthcare quality"],
    "health_system_infrastructure_maintenance": ["hospital infrastructure", "medical facility maintenance", "equipment breakdown"],
    "env_air_quality": ["air quality", "air pollution", "smog", "particulate matter", "respiratory health pollution", "vehicle emissions", "industrial pollution"],
    "env_water_quality": ["water quality", "drinking water safety", "water pollution", "contaminated water supply", "clean water access", "sewage contamination water"],
    "env_sanitation_waste": ["sanitation", "waste management", "sewage system", "hygiene infrastructure", "solid waste disposal", "open defecation"],
    "env_climate_change_health": ["climate change health impact", "heatwave health", "disease vector climate", "extreme weather health", "climate sensitive diseases"],
    "env_extreme_weather_events": ["flood health impact", "heatwave health risk", "storm health", "natural disaster health", "displacement health"],
    "env_food_security_nutrition": ["food security", "nutrition", "malnutrition", "food access", "food prices diet", "hunger", "stunting", "wasting"],
    "env_housing_overcrowding": ["housing conditions", "overcrowding", "homelessness health", "slum health", "inadequate housing"],
    "env_occupational_health": ["occupational health", "workplace safety", "work-related illness", "occupational exposure", "job hazard"],
    "social_determinants_poverty_inequality": ["poverty health", "socioeconomic status health", "health inequality", "health disparity", "social determinants of health"],
    "social_determinants_education_literacy": ["health literacy", "education health", "understanding health information"],
    "social_demographics_age": ["pediatric health", "child health", "geriatric health", "elderly health", "aging population health"],
    "social_demographics_gender": ["women's health", "men's health", "gender health disparities", "maternal health"],
    "social_demographics_vulnerable_groups": ["migrant health", "refugee health", "disability health", "minority health", "vulnerable population health"],
    "social_unrest_conflict_impact": ["conflict health", "social unrest health", "protest health impact", "war health"],
    "social_stigma_discrimination": ["health stigma", "disease stigma", "discrimination healthcare", "hiv stigma", "mental health stigma"],
    "mental_health_symptoms_anxiety": ["anxiety symptoms", "worry", "nervousness", "panic attacks", "anxiety disorder"], # Already had this, refined
    "mental_health_symptoms_depression": ["depression symptoms", "sadness", "hopelessness", "loss of interest", "anhedonia", "depressive disorder", "major depression"],
    "mental_health_symptoms_stress": ["stress symptoms", "overwhelmed", "burnout", "chronic stress", "acute stress"],
    "mental_health_symptoms_sleep": ["sleep problems", "insomnia", "hypersomnia", "sleep disorder", "difficulty sleeping"],
    "mental_health_symptoms_trauma_ptsd": ["trauma symptoms", "ptsd", "post-traumatic stress", "flashbacks", "nightmares trauma"],
    "mental_health_symptoms_psychosis": ["psychosis symptoms", "delusions", "hallucinations", "schizophrenia", "psychotic disorder"],
    "mental_health_substance_use": ["substance abuse", "drug addiction", "alcohol abuse", "opioid crisis", "drug overdose", "substance use disorder"],
    "mental_health_suicide_discourse": ["suicide discussion", "suicidal ideation", "suicide prevention", "self-harm talk"],
    "mental_health_conditions_specific": ["bipolar disorder", "ocd", "obsessive compulsive disorder", "eating disorder", "anorexia", "bulimia", "personality disorder"],
    "mental_health_access_care": ["mental healthcare access", "psychiatrist access", "therapist access", "counseling access", "cost mental health"],
    "mental_health_stigma": ["mental health stigma", "mental illness stigma", "shame mental health"], # Repeated, ensure unique or merge if identical intent
    "mental_health_awareness_support": ["mental health awareness", "mental health support", "wellbeing program", "mental health campaign"],
    "mental_health_impact_crises": ["crisis mental health", "pandemic mental health", "disaster mental health", "economic hardship mental health"],
    "emerging_unexplained_clusters": ["unexplained illness cluster", "mystery illness", "symptom cluster", "disease outbreak unknown"],
    "emerging_atypical_presentations": ["atypical disease symptoms", "unusual disease presentation", "severe disease form"],
    "emerging_antimicrobial_resistance": ["antimicrobial resistance", "amr", "drug-resistant infection", "superbug", "antibiotic resistance", "antibiotic stewardship"],
    "emerging_rare_diseases_uptick": ["rare disease increase", "rare disease outbreak", "orphan disease"],
    "emerging_chemical_radiological_bio_threats": ["chemical threat", "radiological threat", "bioterrorism", "chemical spill health", "radiation leak health", "bioweapon"],
    "emerging_novel_pathogens": ["novel virus", "emerging pathogen", "new bacteria", "unknown pathogen"],
    "emerging_geographic_spread": ["disease spread new area", "geographic expansion disease", "imported disease local transmission"],
    "emerging_zoonotic_spillover_concerns": ["zoonotic spillover", "animal to human transmission new", "wildlife disease human", "bat virus", "rodent virus"],
    "emerging_environmental_links": ["environmental illness link", "pollution illness cluster", "toxin exposure health"],
}

HEALTH_CATEGORIES_KEYWORDS_FR: dict[str, list[str]] = {
    "symptoms_general": ["symptômes généraux", "symptômes systémiques", "fatigue", "malaise", "faiblesse", "variation de poids", "changement d'appétit", "sueurs nocturnes", "asthénie"],
    "symptoms_fever_temperature": ["fièvre", "température élevée", "température basse", "hypothermie", "hyperthermie", "frisson", "grelottement", "température corporelle", "fébrile", "pyrexie"],
    "symptoms_respiratory_upper": ["respiratoire supérieur", "écoulement nasal", "rhinorrhée", "congestion nasale", "éternuement", "mal de gorge", "pharyngite", "perte de voix", "extinction de voix", "enrouement", "laryngite"],
    "symptoms_respiratory_lower": ["respiratoire inférieur", "toux", "toux sèche", "toux productive", "toux grasse", "expectorations", "crachats", "essoufflement", "dyspnée", "respiration sifflante", "oppression thoracique", "douleur thoracique respiration", "hémoptysie"],
    "symptoms_cardiovascular": ["cardiovasculaire", "douleur thoracique", "angine de poitrine", "palpitations", "rythme cardiaque irrégulier", "arythmie", "œdème", "gonflement jambes", "gonflement chevilles", "évanouissement", "syncope", "tension artérielle élevée", "tension artérielle basse", "hypertension", "hypotension"],
    "symptoms_gastrointestinal_upper": ["digestif supérieur", "nausée", "vomissement", "brûlures d'estomac", "reflux acide", "rgo", "indigestion", "dyspepsie", "difficulté à avaler", "dysphagie"],
    "symptoms_gastrointestinal_lower": ["digestif inférieur", "diarrhée", "constipation", "douleur abdominale", "crampes abdominales", "ballonnement", "flatulence", "gaz", "sang dans les selles", "méléna", "rectorragie", "ictère", "jaunisse"],
    "symptoms_neurological": ["neurologique", "mal de tête", "céphalée", "migraine", "étourdissement", "vertige", "confusion", "désorientation", "perte de mémoire", "amnésie", "perte de conscience", "crises épileptiques", "convulsions", "tremblements", "engourdissement", "fourmillement", "paresthésie", "faiblesse musculaire", "paralysie", "problèmes d'équilibre", "ataxie", "perte d'odorat", "anosmie", "perte de goût", "agueusie"],
    "symptoms_musculoskeletal": ["musculo-squelettique", "douleurs musculaires", "myalgie", "douleurs articulaires", "arthralgie", "mal de dos", "douleur cervicale", "raideur", "gonflement articulaire", "crampes musculaires", "douleur osseuse"],
    "symptoms_skin_integumentary": ["symptômes cutanés", "éruption cutanée", "urticaire", "démangeaison", "prurit", "lésions cutanées", "plaies cutanées", "ulcères cutanés", "ampoules", "peau sèche", "desquamation", "changements sudation", "décoloration peau", "perte de cheveux", "alopécie", "changements ongles"],
    "symptoms_eyes_vision": ["symptômes oculaires", "symptômes visuels", "yeux rouges", "conjonctivite", "douleur oculaire", "vision floue", "vision double", "diplopie", "sensibilité lumière", "photophobie", "écoulement oculaire", "perte de vision", "cécité"],
    "symptoms_ears_hearing": ["symptômes auriculaires", "symptômes auditifs", "douleur oreille", "otalgie", "perte d'audition", "surdité", "acouphènes", "bourdonnements oreilles", "écoulement oreille", "otorrhée", "vertige oreille"],
    "symptoms_urinary_renal": ["symptômes urinaires", "symptômes rénaux", "miction douloureuse", "dysurie", "mictions fréquentes", "urgence urinaire", "sang dans l'urine", "hématurie", "incontinence", "douleur au flanc", "diminution débit urinaire", "oligurie", "anurie"],
    "symptoms_reproductive_public": ["santé reproductive", "irrégularités menstruelles", "douleur pelvienne", "saignement anormal", "problèmes fertilité"],
    "symptoms_lymphatic_hematologic": ["symptômes lymphatiques", "symptômes sanguins", "ganglions lymphatiques enflés", "lymphadénopathie", "ecchymoses faciles", "saignement inexpliqué", "anémie", "pétéchies"],
    "disease_covid19": ["covid-19", "covid", "omicron", "variant delta", "covid long", "sars-cov-2", "coronavirus", "pandémie", "symptômes covid", "infection covid"],
    "disease_influenza_seasonal": ["grippe saisonnière", "influenza", "grippe", "h1n1", "h3n2", "virus grippal b", "syndrome grippal"],
    "disease_influenza_avian_pandemic": ["grippe aviaire", "virus h5n1", "virus h7n9", "pandémie grippale", "menace pandémique"],
    "disease_rsv": ["virus respiratoire syncytial", "vrs", "bronchiolite"],
    "disease_common_cold": ["rhume banal", "rhinovirus", "adénovirus rhume", "rhinopharyngite"],
    "disease_measles": ["rougeole", "virus de la rougeole", "taches de koplik", "éruption rougeoleuse"],
    "disease_mumps": ["oreillons", "parotidite", "virus des oreillons", "glandes salivaires enflées"],
    "disease_rubella": ["rubéole", "rougeole allemande", "syndrome de rubéole congénitale"],
    "disease_chickenpox_shingles": ["virus varicelle-zona", "vvz", "varicelle", "zona", "herpès zoster"],
    "disease_tuberculosis": ["tuberculose", "tb", "bacille de koch", "mycobacterium tuberculosis", "tuberculose pulmonaire", "tuberculose extra-pulmonaire", "tuberculose multirésistante", "phtisie"],
    "disease_pertussis": ["coqueluche", "bordetella pertussis"],
    "disease_pneumonia_bacterial": ["pneumonie bactérienne", "streptococcus pneumoniae", "pneumocoque", "haemophilus influenzae pneumonie", "mycoplasma pneumoniae", "légionellose pulmonaire"],
    "disease_diphtheria": ["diphtérie", "corynebacterium diphtheriae"],
    "disease_legionnaires": ["légionellose", "maladie du légionnaire", "legionella pneumophila"],
    "disease_norovirus": ["norovirus", "gastro-entérite aiguë", "grippe intestinale"],
    "disease_rotavirus": ["rotavirus", "vaccin rotavirus", "diarrhée infantile"],
    "disease_salmonellosis": ["salmonelle", "salmonellose", "intoxication alimentaire salmonelle"],
    "disease_shigellosis": ["shigella", "shigellose", "dysenterie bacillaire"],
    "disease_ecoli_pathogenic": ["e. coli pathogène", "ehec", "o157:h7", "stec", "infection e. coli"],
    "disease_campylobacteriosis": ["campylobacter", "campylobactériose", "intoxication campylobacter"],
    "disease_cholera": ["choléra", "vibrio cholerae"],
    "disease_typhoid_paratyphoid": ["fièvre typhoïde", "fièvre entérique", "salmonella typhi", "fièvre paratyphoïde", "salmonella paratyphi"],
    "disease_giardiasis": ["giardia", "giardiase", "giardia lamblia"],
    "disease_amebiasis": ["amibiase", "entamoeba histolytica", "dysenterie amibienne"],
    "disease_listeriosis": ["listéria", "listériose", "listeria monocytogenes", "listériose alimentaire"],
    "disease_hepatitis_a_e": ["hépatite a", "vha", "hépatite e", "vhe", "hépatite alimentaire", "hépatite hydrique"],
    "disease_west_nile_virus": ["virus du nil occidental", "vno", "fièvre du nil occidental", "encéphalite nil occidental", "moustique vno"],
    "disease_dengue": ["dengue", "fièvre dengue", "dengue hémorragique", "moustique aedes dengue"],
    "disease_chikungunya": ["chikungunya", "virus chikungunya", "moustique aedes chikungunya"],
    "disease_leishmaniasis": ["leishmaniose", "leishmaniose cutanée", "leishmaniose viscérale", "kala-azar", "phlébotome leishmaniose"],
    "disease_malaria": ["paludisme", "malaria", "plasmodium falciparum", "plasmodium vivax", "moustique anophèle", "antipaludique"],
    "disease_rift_valley_fever": ["fièvre de la vallée du rift", "fvr", "fvr zoonotique", "fvr moustique"],
    "disease_crimean_congo_hemorrhagic": ["fièvre hémorragique de crimée-congo", "fhcc", "fhcc tique", "fièvre hémorragique virale fhcc"],
    "disease_tick_borne_encephalitis": ["encéphalite à tiques", "eat", "fièvre à tiques"],
    "disease_rabies": ["rage", "hydrophobie", "rage morsure animale", "virus rabique"],
    "disease_brucellosis": ["brucellose", "fièvre de malte", "fièvre ondulante", "brucella"],
    "disease_anthrax": ["anthrax", "charbon bactéridien", "bacillus anthracis", "charbon cutané", "charbon pulmonaire", "charbon intestinal"],
    "disease_leptospirosis": ["leptospirose", "maladie de weil", "leptospira"],
    "disease_q_fever": ["fièvre q", "coxiella burnetii"],
    "disease_mpox": ["mpox", "variole du singe", "orthopoxvirus simien"],
    "disease_ebola_marburg": ["maladie à virus ebola", "mve", "maladie à virus marburg", "mvm", "filovirus", "fièvre hémorragique virale ebola"],
    "disease_scabies_lice": ["gale", "sarcoptes scabiei", "poux de tête", "pédiculose", "lentes", "infestation poux"],
    "disease_hiv_aids": ["vih", "virus de l'immunodéficience humaine", "sida", "syndrome d'immunodéficience acquise", "thérapie antirétrovirale", "trithérapie"],
    "disease_hepatitis_b_c": ["hépatite b", "vhb", "hépatite c", "vhc", "hépatite chronique", "cirrhose hépatique hépatite", "cancer du foie hépatite"],
    "disease_syphilis": ["syphilis", "treponema pallidum", "syphilis congénitale", "neurosyphilis"],
    "disease_gonorrhea": ["gonorrhée", "blennorragie", "neisseria gonorrhoeae"],
    "disease_chlamydia": ["chlamydia", "chlamydia trachomatis", "infection à chlamydia"],
    "disease_hpv": ["papillomavirus humain", "hpv", "cancer du col de l'utérus hpv", "verrues génitales", "vaccin hpv"],
    "disease_meningitis_bacterial": ["méningite bactérienne", "neisseria meningitidis", "méningocoque", "streptococcus pneumoniae méningite", "haemophilus influenzae type b", "hib méningite"],
    "disease_meningitis_viral": ["méningite virale", "méningite aseptique", "entérovirus méningite", "hsv méningite"],
    "disease_tetanus": ["tétanos", "trismus", "clostridium tetani", "anatoxine tétanique"],
    "disease_poliomyelitis": ["polio", "poliomyélite", "poliovirus", "paralysie infantile", "syndrome post-polio", "pvdv"],
    "transmission_airborne_droplet": ["transmission aérienne", "transmission par gouttelettes", "gouttelettes respiratoires", "transmission aérosol"],
    "transmission_foodborne": ["maladie d'origine alimentaire", "intoxication alimentaire", "aliments contaminés", "sécurité alimentaire"],
    "transmission_waterborne": ["maladie d'origine hydrique", "eau contaminée", "sécurité de l'eau", "eau insalubre"],
    "transmission_vector_mosquito": ["maladie transmise par les moustiques", "vecteur moustique", "aedes", "anophèle", "culex"],
    "transmission_vector_tick": ["maladie transmise par les tiques", "vecteur tique", "ixodes", "dermacentor"],
    "transmission_vector_other": ["maladie à transmission vectorielle", "phlébotome", "puce", "mouche vectrice", "mouche tsé-tsé"],
    "transmission_zoonotic": ["maladie zoonotique", "zoonose", "animal à homme", "réservoirs animaux", "transmission interespèce"],
    "transmission_direct_contact": ["transmission par contact direct", "contact peau à peau", "contact muqueuses"],
    "transmission_fecal_oral": ["voie fécale-orale", "contamination fécale", "ingestion orale"],
    "transmission_bloodborne_sexual": ["pathogène transmis par le sang", "infection sexuellement transmissible", "ist", "mst", "transmission fluides corporels"],
    "transmission_healthcare_associated": ["infection associée aux soins", "ias", "infection nosocomiale", "infection hospitalière", "iatrogène"],
    "transmission_congenital_perinatal": ["transmission congénitale", "transmission périnatale", "transmission mère-enfant", "transmission verticale"],
    "disease_type_viral_hemorrhagic": ["fièvre hémorragique virale", "fhv", "ebola", "marburg", "lassa", "fhcc"],
    "disease_type_prion": ["maladie à prions", "maladie de creutzfeldt-jakob", "mcj", "encéphalopathie spongiforme transmissible", "est"],
    "public_health_surveillance_reporting": ["surveillance sanitaire", "déclaration des cas", "rapport épidémiologique", "investigation d'épidémie", "données de santé publique", "nombre de cas"],
    "public_health_prevention_hygiene": ["prévention", "pratiques d'hygiène", "lavage des mains", "hygiène respiratoire", "assainissement", "prévention des maladies"],
    "public_health_vaccination_campaigns": ["campagne de vaccination", "déploiement vaccinal", "éligibilité vaccin", "types de vaccins"],
    "public_health_vaccination_hesitancy": ["hésitation vaccinale", "refus vaccinal", "antivaccination", "mésinformation vaccin", "craintes sécurité vaccin"],
    "public_health_vaccination_access_supply": ["accès vaccin", "approvisionnement vaccin", "pénurie vaccin", "distribution vaccin", "rendez-vous vaccin"],
    "public_health_vaccination_aefi": ["événements indésirables post-vaccinaux", "eipv", "effets secondaires vaccin déclaration"],
    "public_health_npi_distancing_limits": ["distanciation sociale", "distanciation physique", "limites de capacité", "restrictions rassemblements", "confinement"],
    "public_health_npi_closures": ["fermeture écoles", "fermeture commerces", "confinement strict", "couvre-feu", "interventions non pharmaceutiques"],
    "public_health_screening_testing_strategy": ["dépistage maladies", "test diagnostique", "dépistage de masse", "test pcr", "test antigénique rapide", "stratégie de test"],
    "public_health_screening_testing_access": ["disponibilité test", "accessibilité test", "coût test", "centres de dépistage", "autotest"],
    "public_health_contact_tracing": ["recherche des contacts", "notification d'exposition", "enquête de cas"],
    "public_health_quarantine_isolation": ["quarantaine", "isolement", "auto-isolement", "période de quarantaine"],
    "public_health_border_control_travel": ["avis aux voyageurs", "fermeture frontières", "restrictions de voyage", "conditions d'entrée", "contrôle aéroportuaire", "cas importés"],
    "public_health_communication_alerts": ["annonce santé publique", "alerte sanitaire", "communication des risques", "avis sanitaire", "communication d'urgence"],
    "public_health_misinformation_disinformation": ["mésinformation santé", "désinformation santé", "fausses nouvelles santé", "rumeurs santé", "vérification des faits santé"],
    "public_health_policy_legislation": ["politique de santé publique", "législation sanitaire", "réglementation gouvernementale santé", "financement santé"],
    "public_health_vector_control": ["lutte antivectorielle", "démoustication", "prévention tiques", "dératisation", "pulvérisation insecticide"],
    "public_health_food_safety_regulation": ["sécurité sanitaire des aliments", "réglementation alimentaire", "inspection alimentaire", "hygiène restauration"],
    "public_health_research_studies": ["recherche en santé publique", "essai clinique", "étude épidémiologique", "étude sur la santé"],
    "health_system_capacity_hospitals": ["capacité hospitalière", "disponibilité lits", "lits de réanimation", "urgence surchargée", "temps d'attente hôpital"],
    "health_system_capacity_staffing": ["personnel soignant", "pénurie médecins", "pénurie infirmières", "épuisement professionnel soignants", "grève médicale"],
    "health_system_capacity_equipment": ["équipement médical", "pénurie ventilateurs", "approvisionnement oxygène", "pénurie epi", "équipement de protection individuelle"],
    "health_system_access_primary_care": ["accès soins primaires", "accès médecin généraliste", "accès médecin de famille", "soins préventifs", "bilan de santé"],
    "health_system_access_specialist_care": ["accès spécialistes", "consultation spécialiste", "liste d'attente spécialiste", "orientation spécialiste"],
    "health_system_access_geographic_rural": ["soins en milieu rural", "zones sous-desservies", "barrières géographiques accès soins", "cliniques mobiles"],
    "health_system_access_cost_affordability": ["coût des soins", "facture médicale", "reste à charge", "soins abordables", "accessibilité financière soins"],
    "health_system_access_insurance": ["assurance maladie", "cnam", "mutuelle santé", "assurance privée", "sans assurance", "couverture maladie"],
    "health_system_pharmaceuticals_supply": ["approvisionnement médicaments", "pénurie médicaments", "disponibilité pharmacie", "chaîne approvisionnement vaccins"],
    "health_system_pharmaceuticals_cost": ["coût médicaments", "prix des médicaments", "coût ordonnance", "médicaments abordables"],
    "health_system_pharmaceuticals_safety": ["sécurité médicaments", "erreur médicamenteuse", "médicaments contrefaits", "effets indésirables médicaments"],
    "health_system_diagnostics_labs": ["accès laboratoire diagnostic", "disponibilité analyses", "accès imagerie médicale", "retard radiographie irm"],
    "health_system_emergency_services": ["services médicaux d'urgence", "smu", "samu", "temps réponse ambulance", "soins d'urgence"],
    "health_system_telehealth": ["télésanté", "télémédecine", "consultation à distance", "visite médicale virtuelle"],
    "health_system_quality_of_care": ["qualité des soins", "sécurité des patients", "erreur médicale", "satisfaction des patients", "qualité système de santé"],
    "health_system_infrastructure_maintenance": ["infrastructure hospitalière", "maintenance établissements santé", "pannes équipement"],
    "env_air_quality": ["qualité de l'air", "pollution atmosphérique", "smog", "particules fines", "santé respiratoire pollution", "émissions véhicules", "pollution industrielle"],
    "env_water_quality": ["qualité de l'eau", "eau potable", "pollution de l'eau", "approvisionnement eau contaminée", "accès eau propre", "contamination eaux usées"],
    "env_sanitation_waste": ["assainissement", "gestion des déchets", "système d'égouts", "infrastructure hygiène", "élimination déchets solides", "défécation à l'air libre"],
    "env_climate_change_health": ["impact changement climatique santé", "canicule santé", "vecteurs maladies climat", "événements climatiques extrêmes santé", "maladies sensibles climat"],
    "env_extreme_weather_events": ["impact inondation santé", "risque canicule santé", "tempête santé", "catastrophe naturelle santé", "déplacement santé"],
    "env_food_security_nutrition": ["sécurité alimentaire", "nutrition", "malnutrition", "accès nourriture", "prix alimentaires régime", "faim", "retard de croissance", "émaciation"],
    "env_housing_overcrowding": ["conditions de logement", "surpopulation", "sans-abrisme santé", "bidonville santé", "logement insalubre"],
    "env_occupational_health": ["santé au travail", "sécurité au travail", "maladie professionnelle", "exposition professionnelle", "risque professionnel"],
    "social_determinants_poverty_inequality": ["pauvreté santé", "statut socio-économique santé", "inégalité santé", "disparité santé", "déterminants sociaux santé"],
    "social_determinants_education_literacy": ["littératie en santé", "éducation santé", "compréhension information santé"],
    "social_demographics_age": ["santé pédiatrique", "santé infantile", "santé gériatrique", "santé personnes âgées", "vieillissement population santé"],
    "social_demographics_gender": ["santé des femmes", "santé des hommes", "disparités santé genre", "santé maternelle"],
    "social_demographics_vulnerable_groups": ["santé migrants", "santé réfugiés", "santé personnes handicapées", "santé minorités", "santé populations vulnérables"],
    "social_unrest_conflict_impact": ["conflit santé", "troubles sociaux santé", "impact manifestation santé", "guerre santé"],
    "social_stigma_discrimination": ["stigmatisation santé", "stigmatisation maladie", "discrimination soins", "stigmatisation vih", "stigmatisation santé mentale"],
    "mental_health_symptoms_anxiety": ["symptômes anxiété", "inquiétude", "nervosité", "attaques de panique", "trouble anxieux"], # Refined
    "mental_health_symptoms_depression": ["symptômes dépression", "tristesse", "désespoir", "perte d'intérêt", "anhédonie", "trouble dépressif", "dépression majeure"],
    "mental_health_symptoms_stress": ["symptômes stress", "submergé", "épuisement professionnel", "stress chronique", "stress aigu"],
    "mental_health_symptoms_sleep": ["problèmes de sommeil", "insomnie", "hypersomnie", "trouble du sommeil", "difficulté à dormir"],
    "mental_health_symptoms_trauma_ptsd": ["symptômes traumatisme", "tspt", "stress post-traumatique", "flashbacks", "cauchemars traumatisme"],
    "mental_health_symptoms_psychosis": ["symptômes psychose", "délires", "hallucinations", "schizophrénie", "trouble psychotique"],
    "mental_health_substance_use": ["toxicomanie", "abus de substances", "addiction drogues", "abus d'alcool", "crise opioïdes", "overdose", "trouble usage substance"],
    "mental_health_suicide_discourse": ["discours suicidaire", "idées suicidaires", "prévention suicide", "discours automutilation"],
    "mental_health_conditions_specific": ["trouble bipolaire", "toc", "trouble obsessionnel compulsif", "trouble alimentaire", "anorexie", "boulimie", "trouble personnalité"],
    "mental_health_access_care": ["accès soins santé mentale", "accès psychiatre", "accès thérapeute", "accès psychologue", "coût soins santé mentale"],
    "mental_health_stigma": ["stigmatisation santé mentale", "stigmatisation maladie mentale", "honte maladie mentale"],
    "mental_health_awareness_support": ["sensibilisation santé mentale", "soutien santé mentale", "programmes bien-être", "campagne santé mentale"],
    "mental_health_impact_crises": ["crise santé mentale", "pandémie santé mentale", "catastrophe santé mentale", "difficultés économiques santé mentale"],
    "emerging_unexplained_clusters": ["cas groupés inexpliqués", "maladie mystérieuse", "grappe de symptômes", "foyer épidémique inconnu"],
    "emerging_atypical_presentations": ["symptômes atypiques maladie", "présentation inhabituelle maladie", "forme grave maladie"],
    "emerging_antimicrobial_resistance": ["résistance aux antimicrobiens", "ram", "infection résistante aux médicaments", "superbactérie", "antibiorésistance", "bon usage antibiotiques"],
    "emerging_rare_diseases_uptick": ["augmentation maladies rares", "foyer maladie rare", "maladie orpheline"],
    "emerging_chemical_radiological_bio_threats": ["menace chimique", "menace radiologique", "bioterrorisme", "accident chimique santé", "fuite radioactive santé", "arme biologique"],
    "emerging_novel_pathogens": ["nouveau virus", "pathogène émergent", "nouvelle bactérie", "agent pathogène inconnu"],
    "emerging_geographic_spread": ["propagation géographique maladie", "expansion géographique maladie", "transmission locale maladie importée"],
    "emerging_zoonotic_spillover_concerns": ["transmission zoonotique émergente", "saut d'espèce animal homme", "maladie faune sauvage homme", "virus chauve-souris", "virus rongeur"],
    "emerging_environmental_links": ["lien environnement maladie", "pollution maladie groupe", "exposition toxine santé"],
}

HEALTH_CATEGORIES_KEYWORDS_AR: dict[str, list[str]] = {
    # !!! YOU MUST PROVIDE ARABIC KEYWORDS FOR EACH TOPIC KEY (use actual Arabic script) !!!
    "symptoms_general": ["أعراض عامة", "أعراض جهازية", "إرهاق", "توعك", "وهن", "ضعف عام", "تغير في الوزن", "تغير في الشهية", "تعرق ليلي", "فقدان الوزن غير المبرر"],
    "symptoms_fever_temperature": ["حمى", "ارتفاع درجة الحرارة", "انخفاض درجة الحرارة", "نقص الحرارة", "فرط الحرارة", "قشعريرة", "رجفة", "درجة الحرارة الجسدية", "محموم"],
    "symptoms_respiratory_upper": ["الجهاز التنفسي العلوي", "سيلان الأنف", "رشح", "احتقان الأنف", "عطاس", "التهاب الحلق", "التهاب البلعوم", "فقدان الصوت", "بحة في الصوت", "التهاب الحنجرة"],
    "symptoms_respiratory_lower": ["الجهاز التنفسي السفلي", "سعال", "كحة", "سعال جاف", "سعال منتج", "بلغم", "نخامة", "ضيق في التنفس", "عسر التنفس", "صفير عند التنفس", "ضيق في الصدر", "ألم صدري تنفسي", "نفث الدم"],
    "symptoms_cardiovascular": ["قلبي وعائي", "ألم في الصدر", "ذبحة صدرية", "خفقان", "عدم انتظام ضربات القلب", "اضطراب النظم القلبي", "وذمة", "تورم الساقين", "تورم الكاحلين", "إغماء", "غشيان", "ارتفاع ضغط الدم", "انخفاض ضغط الدم", "فرط التوتر الشرياني", "نقص التوتر الشرياني"],
    "symptoms_gastrointestinal_upper": ["الجهاز الهضمي العلوي", "غثيان", "تقيؤ", "استفراغ", "حرقة المعدة", "ارتجاع حمضي", "ارتجاع مريئي", "عسر الهضم", "صعوبة في البلع", "عسر البلع"],
    "symptoms_gastrointestinal_lower": ["الجهاز الهضمي السفلي", "إسهال", "إمساك", "ألم بطني", "مغص بطني", "تقلصات بطنية", "انتفاخ البطن", "غازات", "دم في البراز", "براز أسود", "نزيف شرجي", "يرقان", "اصفرار"],
    "symptoms_neurological": ["عصبي", "صداع", "شقيقة", "دوخة", "دوار", "ارتباك", "تشوش ذهني", "فقدان الذاكرة", "نسيان", "فقدان الوعي", "نوبات", "تشنجات", "رعاش", "خدر", "تنميل", "مذل", "ضعف عضلي", "شلل", "مشاكل في التوازن", "ترنح", "فقدان الشم", "فقدان التذوق"],
    "symptoms_musculoskeletal": ["عضلي هيكلي", "آلام العضلات", "ألم عضلي", "آلام المفاصل", "ألم مفصلي", "ألم الظهر", "ألم الرقبة", "تصلب", "تورم المفاصل", "تشنجات عضلية", "ألم العظام"],
    "symptoms_skin_integumentary": ["أعراض جلدية", "طفح جلدي", "شرى", "حكة", "آفات جلدية", "تقرحات جلدية", "بثور", "جفاف الجلد", "تقشر الجلد", "تغيرات التعرق", "تغير لون الجلد", "تساقط الشعر", "ثعلبة", "تغيرات الأظافر"],
    "symptoms_eyes_vision": ["أعراض العين", "أعراض بصرية", "احمرار العين", "التهاب الملتحمة", "ألم العين", "تشوش الرؤية", "رؤية مزدوجة", "ازدواج الرؤية", "حساسية للضوء", "رهاب الضوء", "إفرازات العين", "فقدان البصر", "عمى"],
    "symptoms_ears_hearing": ["أعراض الأذن", "أعراض سمعية", "ألم الأذن", "فقدان السمع", "صمم", "طنين الأذن", "إفرازات الأذن", "دوار أذني"],
    "symptoms_urinary_renal": ["أعراض بولية", "أعراض كلوية", "عسر التبول", "تبول مؤلم", "كثرة التبول", "إلحاح بولي", "دم في البول", "بيلة دموية", "سلس البول", "ألم الخاصرة", "نقص إدرار البول", "قلة البول", "انقطاع البول"],
    "symptoms_reproductive_public": ["صحة إنجابية", "اضطرابات الدورة الشهرية", "آلام الحوض", "نزيف غير طبيعي", "مشاكل خصوبة"],
    "symptoms_lymphatic_hematologic": ["أعراض لمفاوية", "أعراض دموية", "تورم الغدد الليمفاوية", "تضخم العقد اللمفية", "كدمات سهلة", "نزيف غير مبرر", "فقر الدم", "أنيميا", "نمشات"],
    "disease_covid19": ["كوفيد-19", "كوفيد", "أوميكرون", "متحور دلتا", "كوفيد طويل الأمد", "متلازمة ما بعد كوفيد", "فيروس كورونا", "سارس-كوف-2", "جائحة", "أعراض كوفيد", "عدوى كوفيد"],
    "disease_influenza_seasonal": ["إنفلونزا موسمية", "أنفلونزا", "زكام", "اتش1ان1", "اتش3ان2", "انفلونزا ب", "شبيه بالإنفلونزا"],
    "disease_influenza_avian_pandemic": ["إنفلونزا الطيور", "انفلونزا الطيور", "اتش5ان1", "اتش7ان9", "جائحة إنفلونزا"],
    "disease_rsv": ["الفيروس المخلوي التنفسي", "فيروس RSV", "التهاب القصيبات"],
    "disease_common_cold": ["نزلة برد", "زكام شائع", "فيروسات الأنف", "فيروسات غدانية"],
    "disease_measles": ["حصبة", "فيروس الحصبة", "بقع كوبليك", "طفح الحصبة"],
    "disease_mumps": ["نكاف", "التهاب النكفية", "فيروس النكاف", "تورم الغدد اللعابية"],
    "disease_rubella": ["حصبة ألمانية", "حميراء", "متلازمة الحصبة الألمانية الخلقية"],
    "disease_chickenpox_shingles": ["فيروس جدري الماء النطاقي", "جدري الماء", "الحماق", "الهربس النطاقي", "القوباء المنطقية", "حزام ناري"],
    "disease_tuberculosis": ["سل", "درن", "عصية كوخ", "متفطرة سلية", "سل رئوي", "سل خارج الرئة", "سل مقاوم للأدوية"],
    "disease_pertussis": ["سعال ديكي", "شاهوق", "بورديتيلا شاهوقية"],
    "disease_pneumonia_bacterial": ["التهاب رئوي جرثومي", "ذات الرئة الجرثومية", "مكورات رئوية", "مستدمية نزلية", "مفطورة رئوية"],
    "disease_diphtheria": ["خناق", "ديفتيريا", "وتدية خناقية"],
    "disease_legionnaires": ["داء الفيالقة", "ليجيونيلا"],
    "disease_norovirus": ["نوروفيروس", "التهاب معدة وأمعاء حاد", "انفلونزا المعدة"],
    "disease_rotavirus": ["فيروس عجلي", "روتافيروس", "لقاح روتافيروس", "إسهال الرضع"],
    "disease_salmonellosis": ["سالمونيلا", "داء السلمونيلات", "تسمم غذائي بالسالمونيلا"],
    "disease_shigellosis": ["شيغيلا", "داء الشيغيلات", "زحار عصوي"],
    "disease_ecoli_pathogenic": ["إشريكية قولونية ممرضة", "إي كولاي ممرضة", "EHEC", "O157:H7"],
    "disease_campylobacteriosis": ["عطيفة", "داء العطائف", "تسمم غذائي بالعطيفة"],
    "disease_cholera": ["كوليرا", "ضمة الكوليرا"],
    "disease_typhoid_paratyphoid": ["حمى تيفية", "حمى معوية", "سالمونيلا تيفية", "حمى نظيرة التيفية", "سالمونيلا نظيرة التيفية"],
    "disease_giardiasis": ["جيارديا", "داء الجيارديات", "جيارديا لامبليا"],
    "disease_amebiasis": ["زحار أميبي", "داء الأميبات", "متحولة حالة للنسج"],
    "disease_listeriosis": ["ليستيريا", "داء الليستريات", "ليستيريا مستوحدة", "ليستريوسيس غذائية"],
    "disease_hepatitis_a_e": ["التهاب الكبد أ", "HAV", "التهاب الكبد هـ", "HEV", "التهاب كبد غذائي", "التهاب كبد مائي"],
    "disease_west_nile_virus": ["فيروس غرب النيل", "WNV", "حمى غرب النيل", "التهاب دماغ غرب النيل"],
    "disease_dengue": ["حمى الضنك", "حمى الضنك النزفية", "بعوضة الزاعجة"],
    "disease_chikungunya": ["شيكونغونيا", "فيروس شيكونغونيا"],
    "disease_leishmaniasis": ["ليشمانيا", "داء الليشمانيات", "ليشمانيا جلدية", "ليشمانيا حشوية", "ذبابة الرمل"],
    "disease_malaria": ["ملاريا", "برداء", "متصورة منجلية", "متصورة نشيطة", "بعوضة الأنوفيلة", "مضاد للملاريا"],
    "disease_rift_valley_fever": ["حمى الوادي المتصدع", "RVF", "حمى الوادي المتصدع حيوانية المصدر"],
    "disease_crimean_congo_hemorrhagic": ["حمى القرم الكونغو النزفية", "CCHF", "حمى القرم والكونغو النزفية المنقولة بالقراد"],
    "disease_brucellosis": ["داء البروسيلات", "حمى مالطية", "حمى متموجة", "بروسيلا"],
    "disease_rabies": ["داء الكلب", "سعار", "عضة حيوان مسعور", "فيروس الكلب"],
    "disease_anthrax": ["جمرة خبيثة", "عصوية جمرية", "جمرة جلدية", "جمرة استنشاقية", "جمرة معوية"],
    "disease_leptospirosis": ["داء البريميات", "مرض ويل", "بريمية"],
    "disease_q_fever": ["حمى كيو", "كوكسيلة بورنيتية"],
    "disease_mpox": ["جدري القردة", "إمبوكس", "فيروس جدري القردة"],
    "disease_ebola_marburg": ["مرض فيروس إيبولا", "EVD", "مرض فيروس ماربورغ", "MVD", "فيروس خيطي", "حمى نزفية فيروسية إيبولا"],
    "disease_scabies_lice": ["جرب", "قارمة جربية", "قمل الرأس", "داء القمل", "صئبان"],
    "disease_hiv_aids": ["فيروس نقص المناعة البشرية", "HIV", "إيدز", "متلازمة نقص المناعة المكتسب", "علاج مضاد للفيروسات القهقرية"],
    "disease_hepatitis_b_c": ["التهاب الكبد ب", "HBV", "التهاب الكبد سي", "HCV", "التهاب كبد مزمن", "تليف الكبد", "سرطان الكبد"],
    "disease_syphilis": ["زهري", "سفلس", "لولبية شاحبة", "زهري خلقي", "زهري عصبي"],
    "disease_gonorrhea": ["سيلان", "داء السيلان", "نيسرية بنية"],
    "disease_chlamydia": ["كلاميديا", "متدثرة تراخومية", "عدوى الكلاميديا"],
    "disease_hpv": ["فيروس الورم الحليمي البشري", "HPV", "سرطان عنق الرحم", "ثآليل تناسلية", "لقاح HPV"],
    "disease_meningitis_bacterial": ["التهاب السحايا الجرثومي", "نيسرية سحائية", "مكورات سحائية", "مكورات رئوية سحائية", "مستدمية نزلية نوع ب"],
    "disease_meningitis_viral": ["التهاب السحايا الفيروسي", "التهاب سحايا عقيم", "فيروسات معوية سحائية"],
    "disease_tetanus": ["كزاز", "تيتانوس", "مطثية كزازية", "ذوفان الكزاز"],
    "disease_poliomyelitis": ["شلل الأطفال", "بوليو", "فيروس شلل الأطفال", "شلل رضحي", "متلازمة ما بعد شلل الأطفال"],
    "transmission_airborne_droplet": ["انتقال جوي", "انتقال بالرذاذ", "رذاذ تنفسي", "انتقال بالهباء الجوي", "انتشار عبر الهواء"],
    "transmission_foodborne": ["مرض منقول بالغذاء", "تسمم غذائي", "طعام ملوث", "سلامة الغذاء"],
    "transmission_waterborne": ["مرض منقول بالماء", "ماء ملوث", "سلامة المياه", "مياه غير آمنة"],
    "transmission_vector_mosquito": ["مرض ينقله البعوض", "ناقل البعوض", "زاعجة", "أنوفيلة", "كيولكس"],
    "transmission_vector_tick": ["مرض ينقله القراد", "ناقل القراد", "قرادة"],
    "transmission_vector_other": ["مرض ينقله ناقل آخر", "ذبابة الرمل", "برغوث", "ذبابة ناقلة"],
    "transmission_zoonotic": ["مرض حيواني المصدر", "مرض مشترك بين الإنسان والحيوان", "انتقال من الحيوان للإنسان", "مستودعات حيوانية"],
    "transmission_direct_contact": ["انتقال بالملامسة المباشرة", "ملامسة جلدية", "ملامسة الأغشية المخاطية"],
    "transmission_fecal_oral": ["طريق فموي برازي", "تلوث برازي", "ابتلاع فموي"],
    "transmission_bloodborne_sexual": ["ممرض منقول بالدم", "عدوى منقولة جنسيا", "أمراض منقولة جنسيا", "انتقال بالسوائل الجسدية"],
    "transmission_healthcare_associated": ["عدوى مرتبطة بالرعاية الصحية", "عدوى مكتسبة في المستشفى", "عدوى مستشفيات"],
    "transmission_congenital_perinatal": ["انتقال خلقي", "انتقال ولادي", "انتقال من الأم للطفل", "انتقال عمودي"],
    "disease_type_viral_hemorrhagic": ["حمى نزفية فيروسية", "VHF", "إيبولا", "ماربورغ", "لاسا"],
    "disease_type_prion": ["مرض بريوني", "مرض كروتسفيلد جاكوب", "CJD", "اعتلال دماغي إسفنجي معدي"],
    "public_health_surveillance_reporting": ["مراقبة الأمراض", "تبليغ الحالات", "تقرير وبائي", "تحقيق في فاشية", "بيانات صحة عامة", "عدد الحالات"],
    "public_health_prevention_hygiene": ["وقاية", "ممارسات نظافة", "غسل اليدين", "آداب السعال", "إصحاح", "وقاية من الأمراض"],
    "public_health_vaccination_campaigns": ["حملة تطعيم", "حملة تلقيح", "طرح اللقاح", "أهلية اللقاح", "أنواع اللقاحات"],
    "public_health_vaccination_hesitancy": ["تردد في تلقي اللقاح", "رفض اللقاح", "معاداة التطعيم", "معلومات مضللة عن اللقاح", "مخاوف سلامة اللقاح"],
    "public_health_vaccination_access_supply": ["توفر اللقاح", "إمدادات اللقاح", "نقص اللقاح", "توزيع اللقاح", "موعد تلقيح"],
    "public_health_vaccination_aefi": ["أحداث ضائرة بعد التحصين", "AEFI", "الإبلاغ عن الآثار الجانبية للقاح"],
    "public_health_npi_distancing_limits": ["تباعد اجتماعي", "تباعد جسدي", "حدود السعة", "قيود التجمعات", "أمر البقاء في المنزل"],
    "public_health_npi_closures": ["إغلاق المدارس", "إغلاق الأعمال", "إغلاق تام", "حظر تجول", "تدخلات غير دوائية"],
    "public_health_screening_testing_strategy": ["فحص الأمراض", "اختبار تشخيصي", "اختبار جماعي", "اختبار PCR", "اختبار مستضد سريع", "استراتيجية الاختبار"],
    "public_health_screening_testing_access": ["توفر الاختبار", "إمكانية الوصول للاختبار", "تكلفة الاختبار", "مراكز اختبار", "عدة اختبار منزلية"],
    "public_health_contact_tracing": ["تتبع المخالطين", "إشعار التعرض", "تحقيق في حالة"],
    "public_health_quarantine_isolation": ["حجر صحي", "عزل", "عزل ذاتي", "فترة الحجر"],
    "public_health_border_control_travel": ["تحذيرات السفر", "إغلاق الحدود", "قيود السفر", "شروط الدخول", "فحص المطارات", "حالات وافدة"],
    "public_health_communication_alerts": ["إعلان صحة عامة", "تنبيه صحي", "تواصل بشأن المخاطر", "استشارة صحية", "اتصال طوارئ"],
    "public_health_misinformation_disinformation": ["معلومات صحية مضللة", "معلومات صحية مغلوطة", "أخبار صحية زائفة", "شائعات صحية", "تدقيق الحقائق الصحية"],
    "public_health_policy_legislation": ["سياسة صحة عامة", "تشريعات صحية", "تنظيمات حكومية صحية", "تمويل صحي"],
    "public_health_vector_control": ["مكافحة ناقلات الأمراض", "مكافحة البعوض", "مكافحة القراد", "مكافحة القوارض", "رش مبيدات حشرية"],
    "public_health_food_safety_regulation": ["سلامة الغذاء", "تنظيم الغذاء", "تفتيش غذائي", "نظافة المطاعم"],
    "public_health_research_studies": ["بحث في الصحة العامة", "تجربة سريرية", "دراسة وبائية", "دراسة صحية"],
    "health_system_capacity_hospitals": ["سعة المستشفيات", "توفر الأسرة", "أسرة عناية مركزة", "اكتظاظ غرف الطوارئ", "أوقات انتظار المرضى"],
    "health_system_capacity_staffing": ["كوادر الرعاية الصحية", "نقص الأطباء", "نقص الممرضات", "إرهاق العاملين الصحيين", "إضراب طبي"],
    "health_system_capacity_equipment": ["معدات طبية", "توفر أجهزة التنفس الاصطناعي", "إمدادات الأكسجين", "نقص معدات الوقاية الشخصية"],
    "health_system_access_primary_care": ["وصول للرعاية الأولية", "وصول لطبيب عام", "وصول لطبيب أسرة", "رعاية وقائية", "فحوصات دورية"],
    "health_system_access_specialist_care": ["وصول للأخصائيين", "استشارة أخصائي", "قائمة انتظار أخصائي", "إحالة لأخصائي"],
    "health_system_access_geographic_rural": ["رعاية صحية ريفية", "مناطق محرومة من الخدمات الصحية", "عوائق جغرافية للوصول للرعاية", "عيادات متنقلة"],
    "health_system_access_cost_affordability": ["تكلفة الرعاية الصحية", "فاتورة طبية", "نفقات صحية شخصية", "رعاية صحية ميسورة التكلفة"],
    "health_system_access_insurance": ["تأمين صحي", "كنام", "تأمين صحي خاص", "غير مؤمن عليه", "تغطية تأمينية"],
    "health_system_pharmaceuticals_supply": ["إمدادات الأدوية", "نقص الأدوية", "توفر الأدوية في الصيدليات", "سلسلة إمداد اللقاحات"],
    "health_system_pharmaceuticals_cost": ["تكلفة الأدوية", "سعر الدواء", "تكلفة الوصفة الطبية", "أدوية ميسورة التكلفة"],
    "health_system_pharmaceuticals_safety": ["سلامة الدواء", "خطأ دوائي", "أدوية مغشوشة", "تفاعلات دوائية ضارة"],
    "health_system_diagnostics_labs": ["وصول للمختبرات التشخيصية", "توفر الفحوصات المخبرية", "وصول لخدمات الأشعة", "تأخير أشعة سينية ورنين مغناطيسي"],
    "health_system_emergency_services": ["خدمات طبية طارئة", "EMS", "إسعاف", "وقت استجابة الإسعاف", "رعاية طارئة"],
    "health_system_telehealth": ["صحة عن بعد", "طب عن بعد", "استشارة عن بعد", "زيارة طبيب افتراضية"],
    "health_system_quality_of_care": ["جودة الرعاية", "سلامة المرضى", "خطأ طبي", "رضا المرضى", "جودة النظام الصحي"],
    "health_system_infrastructure_maintenance": ["بنية تحتية للمستشفيات", "صيانة المرافق الصحية", "أعطال المعدات"],
    "env_air_quality": ["جودة الهواء", "تلوث الهواء", "ضباب دخاني", "جسيمات معلقة", "صحة الجهاز التنفسي والتلوث", "انبعاثات المركبات", "تلوث صناعي"],
    "env_water_quality": ["جودة المياه", "سلامة مياه الشرب", "تلوث المياه", "إمدادات مياه ملوثة", "وصول لمياه نظيفة", "تلوث مياه الصرف الصحي"],
    "env_sanitation_waste": ["إصحاح", "إدارة النفايات", "نظام صرف صحي", "بنية تحتية للنظافة", "التخلص من النفايات الصلبة", "تبرز في العراء"],
    "env_climate_change_health": ["تأثير تغير المناخ على الصحة", "موجات الحر والصحة", "ناقلات الأمراض والمناخ", "ظواهر جوية متطرفة والصحة", "أمراض حساسة للمناخ"],
    "env_extreme_weather_events": ["تأثير الفيضانات على الصحة", "مخاطر موجات الحر الصحية", "عواصف وصحة", "كوارث طبيعية وصحة", "نزوح وصحة"],
    "env_food_security_nutrition": ["أمن غذائي", "تغذية", "سوء تغذية", "وصول للغذاء", "أسعار الغذاء والنظام الغذائي", "جوع", "تقزم", "هزال"],
    "env_housing_overcrowding": ["ظروف سكنية", "اكتظاظ سكاني", "تشرد وصحة", "صحة الأحياء الفقيرة", "سكن غير لائق"],
    "env_occupational_health": ["صحة مهنية", "سلامة مكان العمل", "أمراض مهنية", "تعرض مهني", "مخاطر وظيفية"],
    "social_determinants_poverty_inequality": ["فقر وصحة", "وضع اجتماعي اقتصادي وصحة", "لامساواة صحية", "تفاوت صحي", "محددات اجتماعية للصحة"],
    "social_determinants_education_literacy": ["ثقافة صحية", "تعليم وصحة", "فهم المعلومات الصحية"],
    "social_demographics_age": ["صحة الأطفال", "طب الأطفال", "صحة المسنين", "طب الشيخوخة", "شيخوخة السكان والصحة"],
    "social_demographics_gender": ["صحة المرأة", "صحة الرجل", "تفاوتات صحية بين الجنسين", "صحة الأمومة"],
    "social_demographics_vulnerable_groups": ["صحة المهاجرين", "صحة اللاجئين", "صحة ذوي الإعاقة", "صحة الأقليات", "صحة الفئات الضعيفة"],
    "social_unrest_conflict_impact": ["صراع وصحة", "اضطرابات اجتماعية وصحة", "تأثير الاحتجاجات على الصحة", "حرب وصحة"],
    "social_stigma_discrimination": ["وصمة صحية", "وصمة المرض", "تمييز في الرعاية الصحية", "وصمة فيروس نقص المناعة البشرية", "وصمة الصحة النفسية"],
    "mental_health_symptoms_anxiety": ["أعراض القلق", "قلق", "توتر", "عصبية", "نوبات هلع", "اضطراب القلق"],
    "mental_health_symptoms_depression": ["أعراض الاكتئاب", "اكتئاب", "حزن", "يأس", "فقدان الاهتمام", "انعدام التلذذ", "اضطراب اكتئابي"],
    "mental_health_symptoms_stress": ["أعراض الإجهاد", "إجهاد", "مضغوط", "إرهاق مهني", "إجهاد مزمن", "إجهاد حاد"],
    "mental_health_symptoms_sleep": ["مشاكل النوم", "أرق", "فرط النوم", "اضطراب النوم", "صعوبة في النوم"],
    "mental_health_symptoms_trauma_ptsd": ["أعراض الصدمة", "اضطراب ما بعد الصدمة", "PTSD", "ذكريات مؤلمة", "كوابيس مرتبطة بالصدمة"],
    "mental_health_symptoms_psychosis": ["أعراض الذهان", "أوهام", "هلاوس", "فصام", "اضطراب ذهاني"],
    "mental_health_substance_use": ["تعاطي المخدرات", "إدمان المخدرات", "إدمان الكحول", "أزمة المواد الأفيونية", "جرعة زائدة", "اضطراب تعاطي المواد"],
    "mental_health_suicide_discourse": ["حديث عن الانتحار", "أفكار انتحارية", "منع الانتحار", "حديث عن إيذاء النفس"],
    "mental_health_conditions_specific": ["اضطراب ثنائي القطب", "وسواس قهري", "OCD", "اضطراب الأكل", "فقدان الشهية العصبي", "نهام عصبي", "اضطراب الشخصية"],
    "mental_health_access_care": ["وصول لخدمات الصحة النفسية", "وصول لطبيب نفسي", "وصول لمعالج نفسي", "وصول لمرشد نفسي", "تكلفة رعاية الصحة النفسية"],
    "mental_health_stigma": ["وصمة الصحة النفسية", "وصمة المرض النفسي", "عار المرض النفسي"],
    "mental_health_awareness_support": ["توعية بالصحة النفسية", "دعم الصحة النفسية", "برامج الرفاه النفسي", "حملة صحة نفسية"],
    "mental_health_impact_crises": ["أزمة وصحة نفسية", "جائحة وصحة نفسية", "كارثة وصحة نفسية", "صعوبات اقتصادية وصحة نفسية"],
    "emerging_unexplained_clusters": ["مجموعات مرضية غير مفسرة", "مرض غامض", "مجموعة أعراض", "تفشي مرض غير معروف"],
    "emerging_atypical_presentations": ["أعراض مرض غير نمطية", "مظاهر مرض غير معتادة", "شكل حاد للمرض"],
    "emerging_antimicrobial_resistance": ["مقاومة مضادات الميكروبات", "AMR", "عدوى مقاومة للأدوية", "جرثومة خارقة", "مقاومة المضادات الحيوية", "ترشيد استخدام المضادات الحيوية"],
    "emerging_rare_diseases_uptick": ["زيادة الأمراض النادرة", "تفشي مرض نادر", "مرض يتيم"],
    "emerging_chemical_radiological_bio_threats": ["تهديد كيميائي", "تهديد إشعاعي", "إرهاب بيولوجي", "انسكاب كيميائي صحة", "تسرب إشعاعي صحة", "سلاح بيولوجي"],
    "emerging_novel_pathogens": ["فيروس جديد", "ممرض ناشئ", "بكتيريا جديدة", "عامل ممرض غير معروف"],
    "emerging_geographic_spread": ["انتشار جغرافي للمرض", "تمدد جغرافي للمرض", "انتقال محلي لمرض وافد"],
    "emerging_zoonotic_spillover_concerns": ["انتقال حيواني ناشئ", "انتقال المرض من الحيوان للإنسان", "مرض الحياة البرية للإنسان", "فيروس خفافيش", "فيروس قوارض"],
    "emerging_environmental_links": ["صلة بيئية بالمرض", "تلوث وتجمعات مرضية", "تعرض لسموم وصحة"],
}


# Fallback general keywords (lowercase) - built from the specific keyword lists plus extras
# This ensures multilingual coverage for the general fallback.
_all_specific_keywords = []
for lang_dict_key in ['HEALTH_CATEGORIES_KEYWORDS_EN', 'HEALTH_CATEGORIES_KEYWORDS_FR', 'HEALTH_CATEGORIES_KEYWORDS_AR']:
    lang_dict = locals().get(lang_dict_key) # Get dict by name
    if lang_dict: # Check if dictionary is populated
        for kw_list in lang_dict.values():
            _all_specific_keywords.extend([kw.lower() for kw in kw_list])

GENERAL_HEALTH_KEYWORDS_FILTER = list(set(_all_specific_keywords + [
    # Adding some very generic terms again just in case, and ensuring they are lowercased
    "health", "medical", "disease", "symptom", "illness", "clinic", "hospital", "doctor",
    "pharma", "vaccin", "epidemic", "pandemic", "virus", "bacteria", "infection", "outbreak",
    "patient", "treatment", "care", "public health", "cdc", "who", "moh", # Common orgs
    "mortality", "morbidity", "surveillance", "prevention", "control measures",
    "santé", "médical", "maladie", "symptôme", "clinique", "hôpital", "docteur", "médecin",
    "pharmaceutique", "épidémie", "pandémie", "infection", "foyer de maladie",
    "صحة", "طبي", "مرض", "عرض", "مستشفى", "طبيب", "دواء", "صيدلية",
    "لقاح", "وباء", "جائحة", "عدوى", "فيروس", "بكتيريا", "تفشي"
]))
MIN_FILTERED_ARTICLE_LENGTH = 200