# topic_model_pretrainer_cloud/health_topics_data.py
from typing import Dict

# Your HEALTH_TOPICS dictionary
# Ensure descriptions are keyword-rich, space-separated strings for seeding
HEALTH_TOPICS_KEYWORDS: Dict[str, str] = {
    "symptoms_general": "general systemic fatigue malaise weakness weight changes appetite changes night sweats",
    "symptoms_fever_temperature": "Fever high temperature hypothermia chills shivering",
    "symptoms_respiratory_upper": "Upper respiratory symptoms runny nose rhinorrhea nasal congestion sneezing sore throat loss of voice hoarseness",
    "symptoms_respiratory_lower": "Lower respiratory symptoms cough dry productive shortness of breath dyspnea wheezing chest tightness pain breathing",
    "symptoms_cardiovascular": "Cardiovascular symptoms chest pain angina palpitations irregular heartbeat edema swelling legs ankles fainting syncope high low blood pressure",
    "symptoms_gastrointestinal_upper": "Upper GI symptoms nausea vomiting heartburn acid reflux indigestion difficulty swallowing dysphagia",
    "symptoms_gastrointestinal_lower": "Lower GI symptoms diarrhea constipation abdominal pain cramps bloating gas blood stool rectal bleeding jaundice",
    "symptoms_neurological": "Neurological symptoms headache migraine dizziness vertigo confusion disorientation memory loss loss of consciousness seizures convulsions tremors numbness tingling paresthesia weakness paralysis balance problems loss of smell anosmia loss of taste ageusia",
    "symptoms_musculoskeletal": "Musculoskeletal symptoms muscle aches myalgia joint pain arthralgia back pain neck pain stiffness swelling joints muscle cramps bone pain",
    "symptoms_skin_integumentary": "Skin symptoms rash hives urticaria itching pruritus lesions sores ulcers blisters dryness scaling sweating changes skin discoloration hair loss alopecia nail changes",
    "symptoms_eyes_vision": "Eye vision symptoms red eyes conjunctivitis eye pain blurred vision double vision diplopia light sensitivity photophobia eye discharge vision loss",
    "symptoms_ears_hearing": "Ear hearing symptoms ear pain otalgia hearing loss tinnitus ringing ears ear discharge vertigo related ear",
    "symptoms_urinary_renal": "Urinary kidney symptoms painful urination dysuria frequent urination urgency blood urine hematuria incontinence flank pain decreased urine output",
    "symptoms_reproductive_public": "Publicly discussed reproductive health symptoms unusual patterns menstrual irregularities widely pelvic pain reports outbreak",
    "symptoms_lymphatic_hematologic": "Lymphatic Blood symptoms swollen lymph nodes lymphadenopathy easy bruising unexplained bleeding anemia mentions",
    "disease_covid19": "COVID-19 variants Omicron Long COVID PASC coronavirus sars-cov-2",
    "disease_influenza_seasonal": "Seasonal Influenza Flu strains H1N1 H3N2 B grippe",
    "disease_influenza_avian_pandemic": "Avian Influenza Bird Flu H5N1 Pandemic Flu concerns",
    "disease_rsv": "Respiratory Syncytial Virus RSV children elderly",
    "disease_common_cold": "Common Cold Rhinoviruses Adenoviruses non-sars coronaviruses",
    "disease_measles": "Measles virus outbreaks complications rougeole",
    "disease_mumps": "Mumps virus parotitis outbreaks oreillons",
    "disease_rubella": "Rubella German Measles congenital risks rubeole",
    "disease_chickenpox_shingles": "Varicella-Zoster Virus Chickenpox Shingles varicelle zona",
    "disease_tuberculosis": "Tuberculosis TB pulmonary extrapulmonary MDR-TB tuberculose",
    "disease_pertussis": "Pertussis Whooping Cough coqueluche",
    "disease_pneumonia_bacterial": "Bacterial Pneumonia Streptococcus pneumoniae Haemophilus influenzae pneumonie",
    "disease_diphtheria": "Diphtheria diphterie",
    "disease_legionnaires": "Legionnaires disease Legionella legionellose",
    "disease_norovirus": "Norovirus acute gastroenteritis stomach flu gastro",
    "disease_rotavirus": "Rotavirus diarrhea infants",
    "disease_salmonellosis": "Salmonella infection food poisoning salmonellose",
    "disease_shigellosis": "Shigella infection dysentery shigellose",
    "disease_ecoli_pathogenic": "Pathogenic E coli infections EHEC O157 H7",
    "disease_campylobacteriosis": "Campylobacter infection food poisoning",
    "disease_cholera": "Cholera",
    "disease_typhoid_paratyphoid": "Typhoid Fever Paratyphoid Fever fievre typhoide",
    "disease_giardiasis": "Giardia infection giardiase",
    "disease_amebiasis": "Amebiasis Entamoeba histolytica amibiase",
    "disease_listeriosis": "Listeria infection foodborne listeriose",
    "disease_hepatitis_a_e": "Hepatitis A Hepatitis E food waterborne hepatite A E",
    "disease_west_nile_virus": "West Nile Virus mosquito-borne fievre du nil occidental",
    "disease_dengue": "Dengue Fever mosquito-borne",
    "disease_chikungunya": "Chikungunya virus mosquito-borne",
    "disease_leishmaniasis": "Leishmaniasis cutaneous visceral sandfly-borne",
    "disease_malaria": "Malaria mosquito-borne paludisme",
    "disease_rift_valley_fever": "Rift Valley Fever mosquito-borne zoonotic fievre de la vallee du rift",
    "disease_crimean_congo_hemorrhagic": "Crimean-Congo Hemorrhagic Fever CCHF tick-borne fievre hemorragique de crimee-congo",
    "disease_brucellosis": "Brucellosis Malta Fever infected animals products brucellose fievre de malte",
    "disease_rabies": "Rabies animal bites rage",
    "disease_anthrax": "Anthrax cutaneous inhalation gastrointestinal charbon",
    "disease_leptospirosis": "Leptospirosis contaminated water soil animal urine leptospirose",
    "disease_q_fever": "Q Fever Coxiella burnetii inhalation contact animals fievre Q",
    "disease_mpox": "Mpox Monkeypox variole du singe",
    "disease_ebola_marburg": "Ebola Marburg Virus Disease Viral Hemorrhagic Fevers",
    "disease_scabies_lice": "Scabies Head Lice infestations ectoparasites gale poux",
    "disease_hiv_aids": "HIV AIDS Human Immunodeficiency Virus Acquired Immunodeficiency Syndrome SIDA VIH",
    "disease_hepatitis_b_c": "Hepatitis B Hepatitis C bloodborne chronic liver disease hepatite B C",
    "disease_syphilis": "Syphilis",
    "disease_gonorrhea": "Gonorrhea gonorrhee blennorragie",
    "disease_chlamydia": "Chlamydia",
    "disease_hpv": "Human Papillomavirus HPV cancers warts papillomavirus",
    "disease_meningitis_bacterial": "Bacterial Meningitis Neisseria meningitidis Streptococcus pneumoniae Haemophilus influenzae meningite",
    "disease_meningitis_viral": "Viral Meningitis Enteroviruses HSV",
    "disease_tetanus": "Tetanus tetanos",
    "disease_poliomyelitis": "Polio poliomyelitis VDPV",
    "transmission_airborne_droplet": "Diseases spread air respiratory droplets flu measles TB",
    "transmission_foodborne": "Illnesses caused contaminated food",
    "transmission_waterborne": "Illnesses caused contaminated water",
    "transmission_vector_mosquito": "Diseases spread mosquitoes",
    "transmission_vector_tick": "Diseases spread ticks",
    "transmission_vector_other": "Diseases spread other vectors sandflies fleas flies",
    "transmission_zoonotic": "Diseases spread animals humans direct contact bites products aerosols",
    "transmission_direct_contact": "Diseases spread skin-to-skin direct mucous membrane contact",
    "transmission_fecal_oral": "Diseases spread ingestion fecal matter overlaps food waterborne",
    "transmission_bloodborne_sexual": "Diseases spread blood bodily fluids sexual contact STIs Hepatitis HIV",
    "transmission_healthcare_associated": "Healthcare-Associated Infections HAIs nosocomial hospital outbreaks",
    "transmission_congenital_perinatal": "Diseases transmitted mother child pregnancy birth",
    "disease_type_viral_hemorrhagic": "Viral Hemorrhagic Fevers VHFs class Ebola Marburg Lassa CCHF",
    "disease_type_prion": "Prion diseases CJD monitoring unusual neurological clusters",
    "public_health_surveillance_reporting": "Official disease surveillance data releases case counts epidemiological reports outbreak investigations",
    "public_health_prevention_hygiene": "Recommendations discussions personal hygiene handwashing cough etiquette sanitation practices",
    "public_health_vaccination_general": "General discussions vaccines immunization schedules importance vaccination",
    "public_health_vaccination_campaigns": "Specific vaccination campaigns rollout logistics eligibility vaccine types offered",
    "public_health_vaccination_hesitancy": "Vaccine hesitancy safety concerns misinformation anti-vaccination sentiment parental refusal",
    "public_health_vaccination_access_supply": "Vaccine availability shortages distribution challenges access points clinics pharmacies",
    "public_health_vaccination_aefi": "Discussions Adverse Events Following Immunization AEFI monitoring reporting",
    "public_health_npi_masking": "Discussions mask mandates recommendations types masks effectiveness",
    "public_health_npi_distancing_limits": "Social distancing measures capacity limits restrictions gatherings",
    "public_health_npi_closures": "School closures business closures lockdowns curfews",
    "public_health_screening_testing_strategy": "Public health strategies disease screening diagnostic testing mass targeted symptomatic",
    "public_health_screening_testing_access": "Availability accessibility cost location diagnostic tests PCR rapid",
    "public_health_contact_tracing": "Contact tracing efforts methods effectiveness privacy concerns",
    "public_health_quarantine_isolation": "Quarantine isolation policies duration compliance support systems",
    "public_health_border_control_travel": "Travel advisories border closures entry requirements screening ports imported cases",
    "public_health_communication_alerts": "Official public health announcements alerts risk communication messages health advisories",
    "public_health_misinformation_disinformation": "Spread false misleading health information fact-checking efforts rumors",
    "public_health_policy_legislation": "New public health laws regulations government policies funding decisions",
    "public_health_vector_control": "Vector control measures mosquito spraying tick prevention advice rodent control",
    "public_health_food_safety_regulation": "Food safety regulations inspections enforcement actions restaurant grading",
    "public_health_research_studies": "Discussions ongoing public health research clinical trials epidemiological studies",
    "health_system_capacity_hospitals": "Hospital bed availability general ICU emergency room overcrowding wait times",
    "health_system_capacity_staffing": "Healthcare worker shortages doctors nurses technicians burnout strikes workload",
    "health_system_capacity_equipment": "Availability medical equipment ventilators oxygen PPE",
    "health_system_access_primary_care": "Access general practitioners family doctors preventative services check-ups",
    "health_system_access_specialist_care": "Wait times availability specialist consultations procedures",
    "health_system_access_geographic_rural": "Geographic barriers healthcare access issues rural underserved areas",
    "health_system_access_cost_affordability": "Cost healthcare medical bills out-of-pocket expenses affordability issues",
    "health_system_access_insurance": "Health insurance coverage CNAM private insurance issues lack of insurance",
    "health_system_pharmaceuticals_supply": "Medication shortages drug availability pharmacies vaccine supply chain issues",
    "health_system_pharmaceuticals_cost": "Cost medications drug pricing discussions",
    "health_system_pharmaceuticals_safety": "Concerns counterfeit drugs medication errors drug safety",
    "health_system_diagnostics_labs": "Availability delays lab tests imaging services X-ray MRI diagnostic procedures",
    "health_system_emergency_services": "Ambulance response times quality emergency medical services EMS",
    "health_system_telehealth": "Availability usage limitations telemedicine remote consultations",
    "health_system_quality_of_care": "General discussions quality medical treatment patient safety patient satisfaction complaints",
    "health_system_infrastructure_maintenance": "Issues hospital building maintenance equipment breakdowns",
    "env_air_quality": "Air pollution concerns industrial traffic dust storms smog impact respiratory health",
    "env_water_quality": "Drinking water safety water pollution industrial agricultural runoff sewage access clean water",
    "env_sanitation_waste": "Sanitation infrastructure issues sewage management waste disposal problems impact hygiene",
    "env_climate_change_health": "Health impacts climate change heatwaves heat stress changing disease vectors extreme weather events floods droughts",
    "env_extreme_weather_events": "Immediate health impacts floods heatwaves storms injuries displacement waterborne diseases post-flood",
    "env_food_security_nutrition": "Access sufficient safe nutritious food malnutrition impact food prices diet",
    "env_housing_overcrowding": "Housing conditions overcrowding homelessness impact disease transmission mental health",
    "env_occupational_health": "Workplace safety issues occupational exposures chemicals dust noise work-related injuries illnesses",
    "social_determinants_poverty_inequality": "Link poverty socioeconomic status health outcomes health disparities",
    "social_determinants_education_literacy": "Impact education level health literacy understanding health information accessing care",
    "social_demographics_age": "Health issues specific children pediatrics elderly geriatrics",
    "social_demographics_gender": "Gender-specific health issues disparities access outcomes",
    "social_demographics_vulnerable_groups": "Health concerns migrants refugees internally displaced persons people disabilities minority groups",
    "social_unrest_conflict_impact": "Impact social instability protests conflict health services population health",
    "social_stigma_discrimination": "Stigma associated diseases HIV TB mental health impacting care-seeking",
    "mental_health_symptoms_anxiety": "Anxiety worry nervousness panic attacks",
    "mental_health_symptoms_depression": "Depression sadness hopelessness loss of interest fatigue related mood",
    "mental_health_symptoms_stress": "Stress feeling overwhelmed burnout work economy crises",
    "mental_health_symptoms_sleep": "Sleep problems insomnia hypersomnia",
    "mental_health_symptoms_trauma_ptsd": "Trauma-related symptoms PTSD mentions disasters violence",
    "mental_health_symptoms_psychosis": "Discussions psychosis symptoms delusions hallucinations interpret caution",
    "mental_health_substance_use": "Substance abuse addiction drug overdose discussions",
    "mental_health_suicide_discourse": "Discussions related suicide suicidal ideation prevention efforts handle extreme sensitivity ethical considerations",
    "mental_health_conditions_specific": "Mentions specific diagnosed conditions bipolar disorder OCD eating disorders",
    "mental_health_access_care": "Access psychiatrists psychologists therapists counseling services cost mental healthcare",
    "mental_health_stigma": "Stigma surrounding mental illness reluctance seek help",
    "mental_health_awareness_support": "Mental health awareness campaigns support groups wellbeing initiatives",
    "mental_health_impact_crises": "Mental health consequences pandemics economic hardship social upheaval",
    "emerging_unexplained_clusters": "Reports unusual clusters illness symptoms without clear cause",
    "emerging_atypical_presentations": "Known diseases presenting unusual symptoms severity affecting unexpected demographics",
    "emerging_antimicrobial_resistance": "Antimicrobial Resistance AMR drug-resistant infections superbugs antibiotic stewardship discussions",
    "emerging_rare_diseases_uptick": "Increased discussion reports diseases typically rare region",
    "emerging_chemical_radiological_bio_threats": "Concerns rumors reports related chemical spills industrial accidents radiation leaks potential bioterrorism events high sensitivity",
    "emerging_novel_pathogens": "Mentions speculation new viruses bacteria other pathogens",
    "emerging_geographic_spread": "Diseases appearing new geographic locations within Tunisia region",
    "emerging_zoonotic_spillover_concerns": "Concerns diseases jumping animals humans wildlife die-offs potentially linked disease",
    "emerging_environmental_links": "Hypotheses discussions linking specific environmental exposures clusters illness",
}