# topic_model_pretrainer_cloud/filter_keywords/en_filter_keywords.py
from typing import Dict, List

# Keywords for filtering English Wikipedia articles
# These map keys from your MASTER_HEALTH_TOPIC_DESCRIPTIONS_FOR_SEEDING
# to lists of keywords for filtering.
# YOU MUST POPULATE THIS COMPREHENSIVELY.
HEALTH_CATEGORIES_KEYWORDS_EN: dict[str, list[str]] = {
    "symptoms_general": ["general symptoms", "systemic symptoms", "fatigue", "malaise", "weakness", "weight changes", "appetite changes", "night sweats", "asthenia"],
    "symptoms_fever_temperature": ["fever", "high temperature", "hypothermia", "chills", "shivering", "pyrexia", "febrile"],
    "symptoms_respiratory_upper": ["upper respiratory", "runny nose", "rhinorrhea", "nasal congestion", "sneezing", "sore throat", "pharyngitis", "loss of voice", "hoarseness", "laryngitis"],
    "symptoms_respiratory_lower": ["lower respiratory", "cough", "dry cough", "productive cough", "sputum", "shortness of breath", "dyspnea", "wheezing", "chest tightness", "breathing pain", "hemoptysis"],
    "symptoms_cardiovascular": ["cardiovascular", "chest pain", "angina", "palpitations", "irregular heartbeat", "arrhythmia", "edema", "swelling legs", "swelling ankles", "fainting", "syncope", "high blood pressure", "low blood pressure", "hypertension", "hypotension"],
    "symptoms_gastrointestinal_upper": ["upper gi", "nausea", "vomiting", "emesis", "heartburn", "acid reflux", "gerd", "indigestion", "dyspepsia", "difficulty swallowing", "dysphagia"],
    "symptoms_gastrointestinal_lower": ["lower gi", "diarrhea", "constipation", "abdominal pain", "abdominal cramps", "bloating", "flatulence", "gas", "blood in stool", "melena", "rectal bleeding", "jaundice", "icterus"],
    "symptoms_neurological": ["neurological", "headache", "migraine", "dizziness", "vertigo", "confusion", "disorientation", "memory loss", "amnesia", "loss of consciousness", "seizures", "convulsions", "tremors", "numbness", "tingling", "paresthesia", "weakness", "paralysis", "balance problems", "ataxia", "loss of smell", "anosmia", "loss of taste", "ageusia"],
    "symptoms_musculoskeletal": ["musculoskeletal", "muscle aches", "myalgia", "joint pain", "arthralgia", "back pain", "neck pain", "stiffness", "joint swelling", "muscle cramps", "bone pain"],
    "symptoms_skin_integumentary": ["skin symptoms", "rash", "hives", "urticaria", "itching", "pruritus", "lesions", "skin sores", "skin ulcers", "blisters", "dry skin", "scaling skin", "sweating changes", "skin discoloration", "hair loss", "alopecia", "nail changes"],
    "symptoms_eyes_vision": ["eye symptoms", "vision symptoms", "red eyes", "conjunctivitis", "eye pain", "blurred vision", "double vision", "diplopia", "light sensitivity", "photophobia", "eye discharge", "vision loss", "blindness"],
    "symptoms_ears_hearing": ["ear symptoms", "hearing symptoms", "ear pain", "otalgia", "hearing loss", "deafness", "tinnitus", "ringing in ears", "ear discharge", "otorrhea", "vertigo ear"],
    "symptoms_urinary_renal": ["urinary symptoms", "kidney symptoms", "painful urination", "dysuria", "frequent urination", "urinary urgency", "blood in urine", "hematuria", "incontinence", "flank pain", "decreased urine output", "oliguria", "anuria"],
    "symptoms_reproductive_public": ["reproductive health", "menstrual irregularities", "pelvic pain", "abnormal bleeding", "fertility issues"],
    "symptoms_lymphatic_hematologic": ["lymphatic symptoms", "blood symptoms", "swollen lymph nodes", "lymphadenopathy", "easy bruising", "unexplained bleeding", "anemia", "petechiae"],
    "disease_covid19": ["covid-19", "covid", "omicron", "delta variant", "long covid", "pasc", "coronavirus", "sars-cov-2", "pandemic", "covid symptoms", "covid infection"],
    "disease_influenza_seasonal": ["seasonal influenza", "flu", "influenza", "h1n1", "h3n2", "influenza b", "grippe", "influenza-like illness", "ili"],
    "disease_influenza_avian_pandemic": ["avian influenza", "bird flu", "h5n1", "h7n9", "pandemic flu", "influenza pandemic"],
    "disease_rsv": ["respiratory syncytial virus", "rsv", "bronchiolitis"],
    "disease_common_cold": ["common cold", "rhinovirus", "adenovirus cold", "nasopharyngitis"],
    "disease_measles": ["measles", "rubeola", "measles virus", "koplik spots", "measles rash"],
    "disease_mumps": ["mumps", "parotitis", "mumps virus", "swollen salivary glands"],
    "disease_rubella": ["rubella", "german measles", "congenital rubella syndrome"],
    "disease_chickenpox_shingles": ["varicella-zoster virus", "vzv", "chickenpox", "varicella", "shingles", "herpes zoster"],
    "disease_tuberculosis": ["tuberculosis", "tb", "mycobacterium tuberculosis", "pulmonary tb", "extrapulmonary tb", "mdr-tb", "xdr-tb", "consumption"],
    "disease_pertussis": ["pertussis", "whooping cough", "bordetella pertussis"],
    "disease_pneumonia_bacterial": ["bacterial pneumonia", "streptococcus pneumoniae", "pneumococcus", "haemophilus influenzae pneumonia", "mycoplasma pneumonia", "legionella pneumonia"],
    "disease_diphtheria": ["diphtheria", "corynebacterium diphtheriae"],
    "disease_legionnaires": ["legionnaires' disease", "legionellosis", "legionella pneumophila"],
    "disease_norovirus": ["norovirus", "acute gastroenteritis", "stomach flu", "winter vomiting bug"],
    "disease_rotavirus": ["rotavirus", "rotavirus vaccine", "infant diarrhea"],
    "disease_salmonellosis": ["salmonella", "salmonellosis", "food poisoning salmonella", "nontyphoidal salmonella"],
    "disease_shigellosis": ["shigella", "shigellosis", "bacillary dysentery"],
    "disease_ecoli_pathogenic": ["pathogenic e. coli", "ehec", "o157:h7", "stec", "e. coli infection"],
    "disease_campylobacteriosis": ["campylobacter", "campylobacteriosis", "food poisoning campylobacter"],
    "disease_cholera": ["cholera", "vibrio cholerae"],
    "disease_typhoid_paratyphoid": ["typhoid fever", "enteric fever", "salmonella typhi", "paratyphoid fever", "salmonella paratyphi"],
    "disease_giardiasis": ["giardia", "giardiasis", "giardia lamblia", "beaver fever"],
    "disease_amebiasis": ["amebiasis", "entamoeba histolytica", "amebic dysentery"],
    "disease_listeriosis": ["listeria", "listeriosis", "listeria monocytogenes", "foodborne listeria"],
    "disease_hepatitis_a_e": ["hepatitis a", "hav", "hepatitis e", "hev", "foodborne hepatitis", "waterborne hepatitis"],
    "disease_west_nile_virus": ["west nile virus", "wnv", "west nile fever", "west nile encephalitis", "mosquito-borne wnv"],
    "disease_dengue": ["dengue fever", "dengue hemorrhagic fever", "dengue shock syndrome", "breakbone fever", "aedes mosquito dengue"],
    "disease_chikungunya": ["chikungunya", "chikungunya virus", "aedes mosquito chikungunya"],
    "disease_leishmaniasis": ["leishmaniasis", "cutaneous leishmaniasis", "visceral leishmaniasis", "kala-azar", "sandfly leishmaniasis"],
    "disease_malaria": ["malaria", "plasmodium falciparum", "plasmodium vivax", "anopheles mosquito", "antimalarial"],
    "disease_rift_valley_fever": ["rift valley fever", "rvf", "zoonotic rvf", "mosquito-borne rvf"],
    "disease_crimean_congo_hemorrhagic": ["crimean-congo hemorrhagic fever", "cchf", "tick-borne cchf", "viral hemorrhagic fever cchf"],
    "disease_tick_borne_encephalitis": ["tick-borne encephalitis", "tbe", "tick-borne fever"],
    "disease_rabies": ["rabies", "hydrophobia", "animal bite rabies", "rabies virus"],
    "disease_brucellosis": ["brucellosis", "malta fever", "undulant fever", "brucella"],
    "disease_anthrax": ["anthrax", "bacillus anthracis", "cutaneous anthrax", "inhalation anthrax", "gastrointestinal anthrax"],
    "disease_leptospirosis": ["leptospirosis", "weil's disease", "leptospira"],
    "disease_q_fever": ["q fever", "coxiella burnetii"],
    "disease_mpox": ["mpox", "monkeypox", "monkeypox virus"],
    "disease_ebola_marburg": ["ebola virus disease", "evd", "marburg virus disease", "mvd", "filovirus", "viral hemorrhagic fever ebola"],
    "disease_scabies_lice": ["scabies", "sarcoptes scabiei", "head lice", "pediculosis", "nits", "lice infestation"],
    "disease_hiv_aids": ["hiv", "human immunodeficiency virus", "aids", "acquired immunodeficiency syndrome", "antiretroviral therapy", "art"],
    "disease_hepatitis_b_c": ["hepatitis b", "hbv", "hepatitis c", "hcv", "chronic hepatitis", "liver cirrhosis hepatitis", "liver cancer hepatitis"],
    "disease_syphilis": ["syphilis", "treponema pallidum", "congenital syphilis", "neurosyphilis"],
    "disease_gonorrhea": ["gonorrhea", "neisseria gonorrhoeae", "the clap"],
    "disease_chlamydia": ["chlamydia", "chlamydia trachomatis"],
    "disease_hpv": ["human papillomavirus", "hpv", "cervical cancer hpv", "genital warts", "hpv vaccine"],
    "disease_meningitis_bacterial": ["bacterial meningitis", "neisseria meningitidis", "meningococcus", "streptococcus pneumoniae meningitis", "haemophilus influenzae type b", "hib meningitis"],
    "disease_meningitis_viral": ["viral meningitis", "aseptic meningitis", "enterovirus meningitis", "hsv meningitis"],
    "disease_tetanus": ["tetanus", "lockjaw", "clostridium tetani", "tetanus toxoid"],
    "disease_poliomyelitis": ["polio", "poliomyelitis", "poliovirus", "infantile paralysis", "post-polio syndrome", "vdpv"],
    "transmission_airborne_droplet": ["airborne transmission", "droplet transmission", "respiratory droplets", "aerosol transmission", "spread through air"],
    "transmission_foodborne": ["foodborne illness", "food poisoning", "contaminated food", "food safety"],
    "transmission_waterborne": ["waterborne illness", "contaminated water", "water safety", "unsafe water"],
    "transmission_vector_mosquito": ["mosquito-borne disease", "mosquito vector", "aedes", "anopheles", "culex"],
    "transmission_vector_tick": ["tick-borne disease", "tick vector", "ixodes", "dermacentor"],
    "transmission_vector_other": ["vector-borne disease", "sandfly", "flea", "fly vector", "tsetse fly"],
    "transmission_zoonotic": ["zoonotic disease", "zoonosis", "animal to human", "animal reservoirs", "spillover"],
    "transmission_direct_contact": ["direct contact transmission", "skin-to-skin contact", "mucous membrane contact"],
    "transmission_fecal_oral": ["fecal-oral route", "fecal contamination", "oral ingestion"],
    "transmission_bloodborne_sexual": ["bloodborne pathogen", "sexually transmitted infection", "sti", "std", "bodily fluids transmission"],
    "transmission_healthcare_associated": ["healthcare-associated infection", "hai", "nosocomial infection", "hospital-acquired infection", "iatrogenic"],
    "transmission_congenital_perinatal": ["congenital transmission", "perinatal transmission", "mother-to-child transmission", "vertical transmission"],
    "disease_type_viral_hemorrhagic": ["viral hemorrhagic fever", "vhf", "ebola", "marburg", "lassa", "cchf"],
    "disease_type_prion": ["prion disease", "creutzfeldt-jakob disease", "cjd", "transmissible spongiform encephalopathy", "tse"],
    "public_health_surveillance_reporting": ["disease surveillance", "case reporting", "epidemiological report", "outbreak investigation", "public health data", "case counts"],
    "public_health_prevention_hygiene": ["prevention", "hygiene practices", "handwashing", "cough etiquette", "sanitation", "disease prevention"],
    "public_health_vaccination_campaigns": ["vaccination campaign", "immunization drive", "vaccine rollout", "vaccine eligibility", "mass vaccination"],
    "public_health_vaccination_hesitancy": ["vaccine hesitancy", "vaccine refusal", "anti-vaccination", "vaccine misinformation", "vaccine safety concerns"],
    "public_health_vaccination_access_supply": ["vaccine access", "vaccine supply", "vaccine shortage", "vaccine distribution", "vaccine appointment"],
    "public_health_vaccination_aefi": ["adverse events following immunization", "aefi", "vaccine side effects reporting"],
    "public_health_npi_distancing_limits": ["social distancing", "physical distancing", "capacity limits", "gathering restrictions", "stay-at-home order"],
    "public_health_npi_closures": ["school closure", "business closure", "lockdown", "curfew", "non-pharmaceutical interventions"],
    "public_health_screening_testing_strategy": ["disease screening", "diagnostic testing", "mass testing", "pcr test", "rapid antigen test", "testing strategy"],
    "public_health_screening_testing_access": ["test availability", "testing access", "test cost", "testing centers", "home testing kit"],
    "public_health_contact_tracing": ["contact tracing", "exposure notification", "case investigation"],
    "public_health_quarantine_isolation": ["quarantine", "isolation", "self-isolation", "quarantine period"],
    "public_health_border_control_travel": ["travel advisory", "border closure", "travel restrictions", "entry requirements", "airport screening", "imported cases"],
    "public_health_communication_alerts": ["public health announcement", "health alert", "risk communication", "health advisory", "emergency communication"],
    "public_health_misinformation_disinformation": ["health misinformation", "health disinformation", "fake news health", "rumors health", "fact checking health"],
    "public_health_policy_legislation": ["public health policy", "health legislation", "government health regulation", "health funding"],
    "public_health_vector_control": ["vector control", "mosquito control", "tick control", "rodent control", "insecticide spraying"],
    "public_health_food_safety_regulation": ["food safety", "food regulation", "food inspection", "restaurant hygiene"],
    "public_health_research_studies": ["public health research", "clinical trial", "epidemiological study", "health study"],
    "health_system_capacity_hospitals": ["hospital capacity", "bed availability", "icu beds", "emergency room capacity", "hospital overcrowding", "patient wait times"],
    "health_system_capacity_staffing": ["healthcare staffing", "doctor shortage", "nurse shortage", "healthcare worker burnout", "medical staff strike"],
    "health_system_capacity_equipment": ["medical equipment shortage", "ventilator availability", "oxygen supply", "ppe shortage", "personal protective equipment"],
    "health_system_access_primary_care": ["primary care access", "gp access", "family doctor access", "preventive care", "health checkup access"],
    "health_system_access_specialist_care": ["specialist access", "specialist consultation", "wait list specialist", "referral specialist"],
    "health_system_access_geographic_rural": ["rural healthcare", "underserved area healthcare", "geographic access barriers", "mobile clinics"],
    "health_system_access_cost_affordability": ["healthcare cost", "medical bill", "out-of-pocket health expense", "affordable healthcare", "health affordability"],
    "health_system_access_insurance": ["health insurance", "cnam", "private health insurance", "uninsured", "underinsured", "insurance coverage"],
    "health_system_pharmaceuticals_supply": ["medication supply", "drug shortage", "pharmacy stock", "vaccine supply chain"],
    "health_system_pharmaceuticals_cost": ["medication cost", "drug price", "prescription cost", "affordable medicine"],
    "health_system_pharmaceuticals_safety": ["drug safety", "medication error", "counterfeit drug", "adverse drug reaction"],
    "health_system_diagnostics_labs": ["diagnostic lab access", "lab test availability", "imaging service access", "x-ray mri delay"],
    "health_system_emergency_services": ["emergency medical service", "ems", "ambulance service", "ambulance response time", "emergency care"],
    "health_system_telehealth": ["telehealth", "telemedicine", "remote consultation", "virtual doctor visit"],
    "health_system_quality_of_care": ["quality of care", "patient safety", "medical error", "patient satisfaction", "healthcare quality"],
    "health_system_infrastructure_maintenance": ["hospital infrastructure", "medical facility maintenance", "equipment breakdown"],
    "env_air_quality": ["air quality", "air pollution", "smog", "particulate matter", "respiratory health pollution", "vehicle emissions", "industrial pollution"],
    "env_water_quality": ["water quality", "drinking water safety", "water pollution", "contaminated water supply", "clean water access", "sewage contamination water"],
    "env_sanitation_waste": ["sanitation", "waste management", "sewage system", "hygiene infrastructure", "solid waste disposal", "open defecation"],
    "env_climate_change_health": ["climate change health impact", "heatwave health", "disease vector climate", "extreme weather health", "climate sensitive diseases"],
    "env_extreme_weather_events": ["flood health impact", "heatwave health risk", "storm health", "natural disaster health", "displacement health"],
    "env_food_security_nutrition": ["food security", "nutrition", "malnutrition", "food access", "food prices diet", "hunger", "stunting", "wasting"],
    "env_housing_overcrowding": ["housing conditions", "overcrowding", "homelessness health", "slum health", "inadequate housing"],
    "env_occupational_health": ["occupational health", "workplace safety", "work-related illness", "occupational exposure", "job hazard"],
    "social_determinants_poverty_inequality": ["poverty health", "socioeconomic status health", "health inequality", "health disparity", "social determinants of health"],
    "social_determinants_education_literacy": ["health literacy", "education health", "understanding health information"],
    "social_demographics_age": ["pediatric health", "child health", "geriatric health", "elderly health", "aging population health"],
    "social_demographics_gender": ["women's health", "men's health", "gender health disparities", "maternal health"],
    "social_demographics_vulnerable_groups": ["migrant health", "refugee health", "disability health", "minority health", "vulnerable population health"],
    "social_unrest_conflict_impact": ["conflict health", "social unrest health", "protest health impact", "war health"],
    "social_stigma_discrimination": ["health stigma", "disease stigma", "discrimination healthcare", "hiv stigma", "mental health stigma"],
    "mental_health_symptoms_anxiety": ["anxiety symptoms", "worry", "nervousness", "panic attacks", "anxiety disorder"], # Already had this, refined
    "mental_health_symptoms_depression": ["depression symptoms", "sadness", "hopelessness", "loss of interest", "anhedonia", "depressive disorder", "major depression"],
    "mental_health_symptoms_stress": ["stress symptoms", "overwhelmed", "burnout", "chronic stress", "acute stress"],
    "mental_health_symptoms_sleep": ["sleep problems", "insomnia", "hypersomnia", "sleep disorder", "difficulty sleeping"],
    "mental_health_symptoms_trauma_ptsd": ["trauma symptoms", "ptsd", "post-traumatic stress", "flashbacks", "nightmares trauma"],
    "mental_health_symptoms_psychosis": ["psychosis symptoms", "delusions", "hallucinations", "schizophrenia", "psychotic disorder"],
    "mental_health_substance_use": ["substance abuse", "drug addiction", "alcohol abuse", "opioid crisis", "drug overdose", "substance use disorder"],
    "mental_health_suicide_discourse": ["suicide discussion", "suicidal ideation", "suicide prevention", "self-harm talk"],
    "mental_health_conditions_specific": ["bipolar disorder", "ocd", "obsessive compulsive disorder", "eating disorder", "anorexia", "bulimia", "personality disorder"],
    "mental_health_access_care": ["mental healthcare access", "psychiatrist access", "therapist access", "counseling access", "cost mental health"],
    "mental_health_stigma": ["mental health stigma", "mental illness stigma", "shame mental health"], # Repeated, ensure unique or merge if identical intent
    "mental_health_awareness_support": ["mental health awareness", "mental health support", "wellbeing program", "mental health campaign"],
    "mental_health_impact_crises": ["crisis mental health", "pandemic mental health", "disaster mental health", "economic hardship mental health"],
    "emerging_unexplained_clusters": ["unexplained illness cluster", "mystery illness", "symptom cluster", "disease outbreak unknown"],
    "emerging_atypical_presentations": ["atypical disease symptoms", "unusual disease presentation", "severe disease form"],
    "emerging_antimicrobial_resistance": ["antimicrobial resistance", "amr", "drug-resistant infection", "superbug", "antibiotic resistance", "antibiotic stewardship"],
    "emerging_rare_diseases_uptick": ["rare disease increase", "rare disease outbreak", "orphan disease"],
    "emerging_chemical_radiological_bio_threats": ["chemical threat", "radiological threat", "bioterrorism", "chemical spill health", "radiation leak health", "bioweapon"],
    "emerging_novel_pathogens": ["novel virus", "emerging pathogen", "new bacteria", "unknown pathogen"],
    "emerging_geographic_spread": ["disease spread new area", "geographic expansion disease", "imported disease local transmission"],
    "emerging_zoonotic_spillover_concerns": ["zoonotic spillover", "animal to human transmission new", "wildlife disease human", "bat virus", "rodent virus"],
    "emerging_environmental_links": ["environmental illness link", "pollution illness cluster", "toxin exposure health"],
}
