# topic_model_pretrainer_cloud/filter_keywords/fr_filter_keywords.py
from typing import Dict, List

# Keywords for filtering French Wikipedia articles
# YOU MUST POPULATE THIS COMPREHENSIVELY.
HEALTH_CATEGORIES_KEYWORDS_FR: dict[str, list[str]] = {
    "symptoms_general": ["symptômes généraux", "symptômes systémiques", "fatigue", "malaise", "faiblesse", "variation de poids", "changement d'appétit", "sueurs nocturnes", "asthénie"],
    "symptoms_fever_temperature": ["fièvre", "température élevée", "température basse", "hypothermie", "hyperthermie", "frisson", "grelottement", "température corporelle", "fébrile", "pyrexie"],
    "symptoms_respiratory_upper": ["respiratoire supérieur", "écoulement nasal", "rhinorrhée", "congestion nasale", "éternuement", "mal de gorge", "pharyngite", "perte de voix", "extinction de voix", "enrouement", "laryngite"],
    "symptoms_respiratory_lower": ["respiratoire inférieur", "toux", "toux sèche", "toux productive", "toux grasse", "expectorations", "crachats", "essoufflement", "dyspnée", "respiration sifflante", "oppression thoracique", "douleur thoracique respiration", "hémoptysie"],
    "symptoms_cardiovascular": ["cardiovasculaire", "douleur thoracique", "angine de poitrine", "palpitations", "rythme cardiaque irrégulier", "arythmie", "œdème", "gonflement jambes", "gonflement chevilles", "évanouissement", "syncope", "tension artérielle élevée", "tension artérielle basse", "hypertension", "hypotension"],
    "symptoms_gastrointestinal_upper": ["digestif supérieur", "nausée", "vomissement", "brûlures d'estomac", "reflux acide", "rgo", "indigestion", "dyspepsie", "difficulté à avaler", "dysphagie"],
    "symptoms_gastrointestinal_lower": ["digestif inférieur", "diarrhée", "constipation", "douleur abdominale", "crampes abdominales", "ballonnement", "flatulence", "gaz", "sang dans les selles", "méléna", "rectorragie", "ictère", "jaunisse"],
    "symptoms_neurological": ["neurologique", "mal de tête", "céphalée", "migraine", "étourdissement", "vertige", "confusion", "désorientation", "perte de mémoire", "amnésie", "perte de conscience", "crises épileptiques", "convulsions", "tremblements", "engourdissement", "fourmillement", "paresthésie", "faiblesse musculaire", "paralysie", "problèmes d'équilibre", "ataxie", "perte d'odorat", "anosmie", "perte de goût", "agueusie"],
    "symptoms_musculoskeletal": ["musculo-squelettique", "douleurs musculaires", "myalgie", "douleurs articulaires", "arthralgie", "mal de dos", "douleur cervicale", "raideur", "gonflement articulaire", "crampes musculaires", "douleur osseuse"],
    "symptoms_skin_integumentary": ["symptômes cutanés", "éruption cutanée", "urticaire", "démangeaison", "prurit", "lésions cutanées", "plaies cutanées", "ulcères cutanés", "ampoules", "peau sèche", "desquamation", "changements sudation", "décoloration peau", "perte de cheveux", "alopécie", "changements ongles"],
    "symptoms_eyes_vision": ["symptômes oculaires", "symptômes visuels", "yeux rouges", "conjonctivite", "douleur oculaire", "vision floue", "vision double", "diplopie", "sensibilité lumière", "photophobie", "écoulement oculaire", "perte de vision", "cécité"],
    "symptoms_ears_hearing": ["symptômes auriculaires", "symptômes auditifs", "douleur oreille", "otalgie", "perte d'audition", "surdité", "acouphènes", "bourdonnements oreilles", "écoulement oreille", "otorrhée", "vertige oreille"],
    "symptoms_urinary_renal": ["symptômes urinaires", "symptômes rénaux", "miction douloureuse", "dysurie", "mictions fréquentes", "urgence urinaire", "sang dans l'urine", "hématurie", "incontinence", "douleur au flanc", "diminution débit urinaire", "oligurie", "anurie"],
    "symptoms_reproductive_public": ["santé reproductive", "irrégularités menstruelles", "douleur pelvienne", "saignement anormal", "problèmes fertilité"],
    "symptoms_lymphatic_hematologic": ["symptômes lymphatiques", "symptômes sanguins", "ganglions lymphatiques enflés", "lymphadénopathie", "ecchymoses faciles", "saignement inexpliqué", "anémie", "pétéchies"],
    "disease_covid19": ["covid-19", "covid", "omicron", "variant delta", "covid long", "sars-cov-2", "coronavirus", "pandémie", "symptômes covid", "infection covid"],
    "disease_influenza_seasonal": ["grippe saisonnière", "influenza", "grippe", "h1n1", "h3n2", "virus grippal b", "syndrome grippal"],
    "disease_influenza_avian_pandemic": ["grippe aviaire", "virus h5n1", "virus h7n9", "pandémie grippale", "menace pandémique"],
    "disease_rsv": ["virus respiratoire syncytial", "vrs", "bronchiolite"],
    "disease_common_cold": ["rhume banal", "rhinovirus", "adénovirus rhume", "rhinopharyngite"],
    "disease_measles": ["rougeole", "virus de la rougeole", "taches de koplik", "éruption rougeoleuse"],
    "disease_mumps": ["oreillons", "parotidite", "virus des oreillons", "glandes salivaires enflées"],
    "disease_rubella": ["rubéole", "rougeole allemande", "syndrome de rubéole congénitale"],
    "disease_chickenpox_shingles": ["virus varicelle-zona", "vvz", "varicelle", "zona", "herpès zoster"],
    "disease_tuberculosis": ["tuberculose", "tb", "bacille de koch", "mycobacterium tuberculosis", "tuberculose pulmonaire", "tuberculose extra-pulmonaire", "tuberculose multirésistante", "phtisie"],
    "disease_pertussis": ["coqueluche", "bordetella pertussis"],
    "disease_pneumonia_bacterial": ["pneumonie bactérienne", "streptococcus pneumoniae", "pneumocoque", "haemophilus influenzae pneumonie", "mycoplasma pneumoniae", "légionellose pulmonaire"],
    "disease_diphtheria": ["diphtérie", "corynebacterium diphtheriae"],
    "disease_legionnaires": ["légionellose", "maladie du légionnaire", "legionella pneumophila"],
    "disease_norovirus": ["norovirus", "gastro-entérite aiguë", "grippe intestinale"],
    "disease_rotavirus": ["rotavirus", "vaccin rotavirus", "diarrhée infantile"],
    "disease_salmonellosis": ["salmonelle", "salmonellose", "intoxication alimentaire salmonelle"],
    "disease_shigellosis": ["shigella", "shigellose", "dysenterie bacillaire"],
    "disease_ecoli_pathogenic": ["e. coli pathogène", "ehec", "o157:h7", "stec", "infection e. coli"],
    "disease_campylobacteriosis": ["campylobacter", "campylobactériose", "intoxication campylobacter"],
    "disease_cholera": ["choléra", "vibrio cholerae"],
    "disease_typhoid_paratyphoid": ["fièvre typhoïde", "fièvre entérique", "salmonella typhi", "fièvre paratyphoïde", "salmonella paratyphi"],
    "disease_giardiasis": ["giardia", "giardiase", "giardia lamblia"],
    "disease_amebiasis": ["amibiase", "entamoeba histolytica", "dysenterie amibienne"],
    "disease_listeriosis": ["listéria", "listériose", "listeria monocytogenes", "listériose alimentaire"],
    "disease_hepatitis_a_e": ["hépatite a", "vha", "hépatite e", "vhe", "hépatite alimentaire", "hépatite hydrique"],
    "disease_west_nile_virus": ["virus du nil occidental", "vno", "fièvre du nil occidental", "encéphalite nil occidental", "moustique vno"],
    "disease_dengue": ["dengue", "fièvre dengue", "dengue hémorragique", "moustique aedes dengue"],
    "disease_chikungunya": ["chikungunya", "virus chikungunya", "moustique aedes chikungunya"],
    "disease_leishmaniasis": ["leishmaniose", "leishmaniose cutanée", "leishmaniose viscérale", "kala-azar", "phlébotome leishmaniose"],
    "disease_malaria": ["paludisme", "malaria", "plasmodium falciparum", "plasmodium vivax", "moustique anophèle", "antipaludique"],
    "disease_rift_valley_fever": ["fièvre de la vallée du rift", "fvr", "fvr zoonotique", "fvr moustique"],
    "disease_crimean_congo_hemorrhagic": ["fièvre hémorragique de crimée-congo", "fhcc", "fhcc tique", "fièvre hémorragique virale fhcc"],
    "disease_tick_borne_encephalitis": ["encéphalite à tiques", "eat", "fièvre à tiques"],
    "disease_rabies": ["rage", "hydrophobie", "rage morsure animale", "virus rabique"],
    "disease_brucellosis": ["brucellose", "fièvre de malte", "fièvre ondulante", "brucella"],
    "disease_anthrax": ["anthrax", "charbon bactéridien", "bacillus anthracis", "charbon cutané", "charbon pulmonaire", "charbon intestinal"],
    "disease_leptospirosis": ["leptospirose", "maladie de weil", "leptospira"],
    "disease_q_fever": ["fièvre q", "coxiella burnetii"],
    "disease_mpox": ["mpox", "variole du singe", "orthopoxvirus simien"],
    "disease_ebola_marburg": ["maladie à virus ebola", "mve", "maladie à virus marburg", "mvm", "filovirus", "fièvre hémorragique virale ebola"],
    "disease_scabies_lice": ["gale", "sarcoptes scabiei", "poux de tête", "pédiculose", "lentes", "infestation poux"],
    "disease_hiv_aids": ["vih", "virus de l'immunodéficience humaine", "sida", "syndrome d'immunodéficience acquise", "thérapie antirétrovirale", "trithérapie"],
    "disease_hepatitis_b_c": ["hépatite b", "vhb", "hépatite c", "vhc", "hépatite chronique", "cirrhose hépatique hépatite", "cancer du foie hépatite"],
    "disease_syphilis": ["syphilis", "treponema pallidum", "syphilis congénitale", "neurosyphilis"],
    "disease_gonorrhea": ["gonorrhée", "blennorragie", "neisseria gonorrhoeae"],
    "disease_chlamydia": ["chlamydia", "chlamydia trachomatis", "infection à chlamydia"],
    "disease_hpv": ["papillomavirus humain", "hpv", "cancer du col de l'utérus hpv", "verrues génitales", "vaccin hpv"],
    "disease_meningitis_bacterial": ["méningite bactérienne", "neisseria meningitidis", "méningocoque", "streptococcus pneumoniae méningite", "haemophilus influenzae type b", "hib méningite"],
    "disease_meningitis_viral": ["méningite virale", "méningite aseptique", "entérovirus méningite", "hsv méningite"],
    "disease_tetanus": ["tétanos", "trismus", "clostridium tetani", "anatoxine tétanique"],
    "disease_poliomyelitis": ["polio", "poliomyélite", "poliovirus", "paralysie infantile", "syndrome post-polio", "pvdv"],
    "transmission_airborne_droplet": ["transmission aérienne", "transmission par gouttelettes", "gouttelettes respiratoires", "transmission aérosol"],
    "transmission_foodborne": ["maladie d'origine alimentaire", "intoxication alimentaire", "aliments contaminés", "sécurité alimentaire"],
    "transmission_waterborne": ["maladie d'origine hydrique", "eau contaminée", "sécurité de l'eau", "eau insalubre"],
    "transmission_vector_mosquito": ["maladie transmise par les moustiques", "vecteur moustique", "aedes", "anophèle", "culex"],
    "transmission_vector_tick": ["maladie transmise par les tiques", "vecteur tique", "ixodes", "dermacentor"],
    "transmission_vector_other": ["maladie à transmission vectorielle", "phlébotome", "puce", "mouche vectrice", "mouche tsé-tsé"],
    "transmission_zoonotic": ["maladie zoonotique", "zoonose", "animal à homme", "réservoirs animaux", "transmission interespèce"],
    "transmission_direct_contact": ["transmission par contact direct", "contact peau à peau", "contact muqueuses"],
    "transmission_fecal_oral": ["voie fécale-orale", "contamination fécale", "ingestion orale"],
    "transmission_bloodborne_sexual": ["pathogène transmis par le sang", "infection sexuellement transmissible", "ist", "mst", "transmission fluides corporels"],
    "transmission_healthcare_associated": ["infection associée aux soins", "ias", "infection nosocomiale", "infection hospitalière", "iatrogène"],
    "transmission_congenital_perinatal": ["transmission congénitale", "transmission périnatale", "transmission mère-enfant", "transmission verticale"],
    "disease_type_viral_hemorrhagic": ["fièvre hémorragique virale", "fhv", "ebola", "marburg", "lassa", "fhcc"],
    "disease_type_prion": ["maladie à prions", "maladie de creutzfeldt-jakob", "mcj", "encéphalopathie spongiforme transmissible", "est"],
    "public_health_surveillance_reporting": ["surveillance sanitaire", "déclaration des cas", "rapport épidémiologique", "investigation d'épidémie", "données de santé publique", "nombre de cas"],
    "public_health_prevention_hygiene": ["prévention", "pratiques d'hygiène", "lavage des mains", "hygiène respiratoire", "assainissement", "prévention des maladies"],
    "public_health_vaccination_campaigns": ["campagne de vaccination", "déploiement vaccinal", "éligibilité vaccin", "types de vaccins"],
    "public_health_vaccination_hesitancy": ["hésitation vaccinale", "refus vaccinal", "antivaccination", "mésinformation vaccin", "craintes sécurité vaccin"],
    "public_health_vaccination_access_supply": ["accès vaccin", "approvisionnement vaccin", "pénurie vaccin", "distribution vaccin", "rendez-vous vaccin"],
    "public_health_vaccination_aefi": ["événements indésirables post-vaccinaux", "eipv", "effets secondaires vaccin déclaration"],
    "public_health_npi_distancing_limits": ["distanciation sociale", "distanciation physique", "limites de capacité", "restrictions rassemblements", "confinement"],
    "public_health_npi_closures": ["fermeture écoles", "fermeture commerces", "confinement strict", "couvre-feu", "interventions non pharmaceutiques"],
    "public_health_screening_testing_strategy": ["dépistage maladies", "test diagnostique", "dépistage de masse", "test pcr", "test antigénique rapide", "stratégie de test"],
    "public_health_screening_testing_access": ["disponibilité test", "accessibilité test", "coût test", "centres de dépistage", "autotest"],
    "public_health_contact_tracing": ["recherche des contacts", "notification d'exposition", "enquête de cas"],
    "public_health_quarantine_isolation": ["quarantaine", "isolement", "auto-isolement", "période de quarantaine"],
    "public_health_border_control_travel": ["avis aux voyageurs", "fermeture frontières", "restrictions de voyage", "conditions d'entrée", "contrôle aéroportuaire", "cas importés"],
    "public_health_communication_alerts": ["annonce santé publique", "alerte sanitaire", "communication des risques", "avis sanitaire", "communication d'urgence"],
    "public_health_misinformation_disinformation": ["mésinformation santé", "désinformation santé", "fausses nouvelles santé", "rumeurs santé", "vérification des faits santé"],
    "public_health_policy_legislation": ["politique de santé publique", "législation sanitaire", "réglementation gouvernementale santé", "financement santé"],
    "public_health_vector_control": ["lutte antivectorielle", "démoustication", "prévention tiques", "dératisation", "pulvérisation insecticide"],
    "public_health_food_safety_regulation": ["sécurité sanitaire des aliments", "réglementation alimentaire", "inspection alimentaire", "hygiène restauration"],
    "public_health_research_studies": ["recherche en santé publique", "essai clinique", "étude épidémiologique", "étude sur la santé"],
    "health_system_capacity_hospitals": ["capacité hospitalière", "disponibilité lits", "lits de réanimation", "urgence surchargée", "temps d'attente hôpital"],
    "health_system_capacity_staffing": ["personnel soignant", "pénurie médecins", "pénurie infirmières", "épuisement professionnel soignants", "grève médicale"],
    "health_system_capacity_equipment": ["équipement médical", "pénurie ventilateurs", "approvisionnement oxygène", "pénurie epi", "équipement de protection individuelle"],
    "health_system_access_primary_care": ["accès soins primaires", "accès médecin généraliste", "accès médecin de famille", "soins préventifs", "bilan de santé"],
    "health_system_access_specialist_care": ["accès spécialistes", "consultation spécialiste", "liste d'attente spécialiste", "orientation spécialiste"],
    "health_system_access_geographic_rural": ["soins en milieu rural", "zones sous-desservies", "barrières géographiques accès soins", "cliniques mobiles"],
    "health_system_access_cost_affordability": ["coût des soins", "facture médicale", "reste à charge", "soins abordables", "accessibilité financière soins"],
    "health_system_access_insurance": ["assurance maladie", "cnam", "mutuelle santé", "assurance privée", "sans assurance", "couverture maladie"],
    "health_system_pharmaceuticals_supply": ["approvisionnement médicaments", "pénurie médicaments", "disponibilité pharmacie", "chaîne approvisionnement vaccins"],
    "health_system_pharmaceuticals_cost": ["coût médicaments", "prix des médicaments", "coût ordonnance", "médicaments abordables"],
    "health_system_pharmaceuticals_safety": ["sécurité médicaments", "erreur médicamenteuse", "médicaments contrefaits", "effets indésirables médicaments"],
    "health_system_diagnostics_labs": ["accès laboratoire diagnostic", "disponibilité analyses", "accès imagerie médicale", "retard radiographie irm"],
    "health_system_emergency_services": ["services médicaux d'urgence", "smu", "samu", "temps réponse ambulance", "soins d'urgence"],
    "health_system_telehealth": ["télésanté", "télémédecine", "consultation à distance", "visite médicale virtuelle"],
    "health_system_quality_of_care": ["qualité des soins", "sécurité des patients", "erreur médicale", "satisfaction des patients", "qualité système de santé"],
    "health_system_infrastructure_maintenance": ["infrastructure hospitalière", "maintenance établissements santé", "pannes équipement"],
    "env_air_quality": ["qualité de l'air", "pollution atmosphérique", "smog", "particules fines", "santé respiratoire pollution", "émissions véhicules", "pollution industrielle"],
    "env_water_quality": ["qualité de l'eau", "eau potable", "pollution de l'eau", "approvisionnement eau contaminée", "accès eau propre", "contamination eaux usées"],
    "env_sanitation_waste": ["assainissement", "gestion des déchets", "système d'égouts", "infrastructure hygiène", "élimination déchets solides", "défécation à l'air libre"],
    "env_climate_change_health": ["impact changement climatique santé", "canicule santé", "vecteurs maladies climat", "événements climatiques extrêmes santé", "maladies sensibles climat"],
    "env_extreme_weather_events": ["impact inondation santé", "risque canicule santé", "tempête santé", "catastrophe naturelle santé", "déplacement santé"],
    "env_food_security_nutrition": ["sécurité alimentaire", "nutrition", "malnutrition", "accès nourriture", "prix alimentaires régime", "faim", "retard de croissance", "émaciation"],
    "env_housing_overcrowding": ["conditions de logement", "surpopulation", "sans-abrisme santé", "bidonville santé", "logement insalubre"],
    "env_occupational_health": ["santé au travail", "sécurité au travail", "maladie professionnelle", "exposition professionnelle", "risque professionnel"],
    "social_determinants_poverty_inequality": ["pauvreté santé", "statut socio-économique santé", "inégalité santé", "disparité santé", "déterminants sociaux santé"],
    "social_determinants_education_literacy": ["littératie en santé", "éducation santé", "compréhension information santé"],
    "social_demographics_age": ["santé pédiatrique", "santé infantile", "santé gériatrique", "santé personnes âgées", "vieillissement population santé"],
    "social_demographics_gender": ["santé des femmes", "santé des hommes", "disparités santé genre", "santé maternelle"],
    "social_demographics_vulnerable_groups": ["santé migrants", "santé réfugiés", "santé personnes handicapées", "santé minorités", "santé populations vulnérables"],
    "social_unrest_conflict_impact": ["conflit santé", "troubles sociaux santé", "impact manifestation santé", "guerre santé"],
    "social_stigma_discrimination": ["stigmatisation santé", "stigmatisation maladie", "discrimination soins", "stigmatisation vih", "stigmatisation santé mentale"],
    "mental_health_symptoms_anxiety": ["symptômes anxiété", "inquiétude", "nervosité", "attaques de panique", "trouble anxieux"], # Refined
    "mental_health_symptoms_depression": ["symptômes dépression", "tristesse", "désespoir", "perte d'intérêt", "anhédonie", "trouble dépressif", "dépression majeure"],
    "mental_health_symptoms_stress": ["symptômes stress", "submergé", "épuisement professionnel", "stress chronique", "stress aigu"],
    "mental_health_symptoms_sleep": ["problèmes de sommeil", "insomnie", "hypersomnie", "trouble du sommeil", "difficulté à dormir"],
    "mental_health_symptoms_trauma_ptsd": ["symptômes traumatisme", "tspt", "stress post-traumatique", "flashbacks", "cauchemars traumatisme"],
    "mental_health_symptoms_psychosis": ["symptômes psychose", "délires", "hallucinations", "schizophrénie", "trouble psychotique"],
    "mental_health_substance_use": ["toxicomanie", "abus de substances", "addiction drogues", "abus d'alcool", "crise opioïdes", "overdose", "trouble usage substance"],
    "mental_health_suicide_discourse": ["discours suicidaire", "idées suicidaires", "prévention suicide", "discours automutilation"],
    "mental_health_conditions_specific": ["trouble bipolaire", "toc", "trouble obsessionnel compulsif", "trouble alimentaire", "anorexie", "boulimie", "trouble personnalité"],
    "mental_health_access_care": ["accès soins santé mentale", "accès psychiatre", "accès thérapeute", "accès psychologue", "coût soins santé mentale"],
    "mental_health_stigma": ["stigmatisation santé mentale", "stigmatisation maladie mentale", "honte maladie mentale"],
    "mental_health_awareness_support": ["sensibilisation santé mentale", "soutien santé mentale", "programmes bien-être", "campagne santé mentale"],
    "mental_health_impact_crises": ["crise santé mentale", "pandémie santé mentale", "catastrophe santé mentale", "difficultés économiques santé mentale"],
    "emerging_unexplained_clusters": ["cas groupés inexpliqués", "maladie mystérieuse", "grappe de symptômes", "foyer épidémique inconnu"],
    "emerging_atypical_presentations": ["symptômes atypiques maladie", "présentation inhabituelle maladie", "forme grave maladie"],
    "emerging_antimicrobial_resistance": ["résistance aux antimicrobiens", "ram", "infection résistante aux médicaments", "superbactérie", "antibiorésistance", "bon usage antibiotiques"],
    "emerging_rare_diseases_uptick": ["augmentation maladies rares", "foyer maladie rare", "maladie orpheline"],
    "emerging_chemical_radiological_bio_threats": ["menace chimique", "menace radiologique", "bioterrorisme", "accident chimique santé", "fuite radioactive santé", "arme biologique"],
    "emerging_novel_pathogens": ["nouveau virus", "pathogène émergent", "nouvelle bactérie", "agent pathogène inconnu"],
    "emerging_geographic_spread": ["propagation géographique maladie", "expansion géographique maladie", "transmission locale maladie importée"],
    "emerging_zoonotic_spillover_concerns": ["transmission zoonotique émergente", "saut d'espèce animal homme", "maladie faune sauvage homme", "virus chauve-souris", "virus rongeur"],
    "emerging_environmental_links": ["lien environnement maladie", "pollution maladie groupe", "exposition toxine santé"],
}
